--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-1.pgdg20.04+1)
-- Dumped by pg_dump version 17.2 (Ubuntu 17.2-1.pgdg20.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: couch_management_sofa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.couch_management_sofa (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    image character varying(100) NOT NULL,
    price double precision NOT NULL,
    original_price double precision NOT NULL,
    discount double precision NOT NULL,
    quantity integer NOT NULL,
    description text,
    features jsonb
);


ALTER TABLE public.couch_management_sofa OWNER TO postgres;

--
-- Name: couch_management_sofa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.couch_management_sofa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.couch_management_sofa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add sofa	7	add_sofa
26	Can change sofa	7	change_sofa
27	Can delete sofa	7	delete_sofa
28	Can view sofa	7	view_sofa
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$hJbfUJC3tM671tqsEgjqvb$V10apdYnll3jBHakmECJD02oYTC1aoVZoXeAbhJd548=	2025-01-16 16:53:01.664503+05:30	t	admin				t	t	2025-01-16 16:52:01.093317+05:30
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: couch_management_sofa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.couch_management_sofa (id, name, image, price, original_price, discount, quantity, description, features) FROM stdin;
17	Napper Plus Sofa -Three Seater Reflection Rose Brown	sofa_images/sofa_15_lZf8jo5.jpg	33998	26178.46	23	1		{"hex_color": "#808080", "rgb_color": [150, 109, 112], "class_name": "3-Seater", "color_name": "gray"}
3	Flipper Sofa Cum Bed - Three Seater (6'x5') Feet- WarpKnit\n                      Grey	sofa_images/sofa_1_nFSO1Jk.jpg	8999	6209.3099999999995	31	1		{"hex_color": "#a9a9a9", "rgb_color": [192, 181, 167], "class_name": "2-Seater", "color_name": "darkgray"}
4	Solatio Sofa - Three Seater	sofa_images/sofa_2_XYfUwZj.jpg	11998	9358.44	22	1		{"hex_color": "#c0c0c0", "rgb_color": [187, 181, 178], "class_name": "3-Seater", "color_name": "silver"}
5	Solomon Sofa - Three Seater	sofa_images/sofa_3_apgHjjn.jpg	32999	21449.35	35	1		{"hex_color": "#808080", "rgb_color": [150, 141, 126], "class_name": "2-Seater", "color_name": "gray"}
6	Napper Sofa - Three Seater	sofa_images/sofa_4_5fI2NQG.jpg	25000	21000	16	1		{"hex_color": "#f8f8ff", "rgb_color": [249, 250, 250], "class_name": "3-Seater", "color_name": "ghostwhite"}
7	Amoeba Sofa cum Bed	sofa_images/sofa_5_500YJJc.jpg	22157	15953.04	28	1		{"hex_color": "#808080", "rgb_color": [148, 145, 129], "class_name": "2-Seater", "color_name": "gray"}
8	Barcelona L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_6_BLz4YyU.jpg	40407	35558.16	12	1		{"hex_color": "#d3d3d3", "rgb_color": [222, 216, 203], "class_name": "L-Shape", "color_name": "lightgray"}
9	Naxos Sofa - Three Seater	sofa_images/sofa_7_hePw3ZB.jpg	45499	29574.35	35	1		{"hex_color": "#d3d3d3", "rgb_color": [218, 201, 186], "class_name": "2-Seater", "color_name": "lightgray"}
10	Belize L Shape Sofa Set (3 Seater + Left Aligned Chaise)	sofa_images/sofa_8_aZS9lzf.jpg	32694	27789.9	15	1		{"hex_color": "#faebd7", "rgb_color": [239, 229, 220], "class_name": "L-Shape", "color_name": "antiquewhite"}
11	Skiver L Shape 6 Seater Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_9_0rMIYjs.jpg	26000	17680	32	1		{"hex_color": "#d3d3d3", "rgb_color": [213, 207, 198], "class_name": "L-Shape", "color_name": "lightgray"}
12	Azores Sofa - Three Seater	sofa_images/sofa_10_JeAlRVM.jpg	33999	22099.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [194, 186, 173], "class_name": "2-Seater", "color_name": "silver"}
13	Lumara Sofa -Three Seater	sofa_images/sofa_11_31fIIET.jpg	25999	16899.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [205, 189, 175], "class_name": "3-Seater", "color_name": "silver"}
14	Tahiti Sofa - Three Seater	sofa_images/sofa_12_LtZ3mLP.jpg	37999	24699.35	35	1		{"hex_color": "#ffe4c4", "rgb_color": [236, 215, 202], "class_name": "2-Seater", "color_name": "bisque"}
15	Belize Plus L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_13_B1OiIiP.jpg	49449	42526.14	14	1		{"hex_color": "#a9a9a9", "rgb_color": [172, 173, 175], "class_name": "L-Shape", "color_name": "darkgray"}
16	Dreamer Plus Sofa -Three Seater	sofa_images/sofa_14_JgeuAkR.jpg	35498	26268.52	26	1		{"hex_color": "#c0c0c0", "rgb_color": [194, 183, 179], "class_name": "2-Seater", "color_name": "silver"}
18	Tuvalu Sofa without Motion - Three Seater	sofa_images/sofa_16_EsHEehE.jpg	39999	25999.35	35	1		{"hex_color": "#d3d3d3", "rgb_color": [223, 217, 205], "class_name": "L-Shape", "color_name": "lightgray"}
19	Komodo Sofa - Three Seater	sofa_images/sofa_17_dga0wyE.jpg	37499	24374.35	35	1		{"hex_color": "#d3d3d3", "rgb_color": [213, 204, 193], "class_name": "3-Seater", "color_name": "lightgray"}
20	SnoozePro Sofa - Three Seater	sofa_images/sofa_18_agUt1ly.jpg	19600	14504	26	1		{"hex_color": "#faf0e6", "rgb_color": [240, 238, 229], "class_name": "3-Seater", "color_name": "linen"}
21	Sicily Sofa - Three Seater	sofa_images/sofa_19_e2JyAqF.jpg	16999	13769.19	19	1		{"hex_color": "#dcdcdc", "rgb_color": [225, 223, 221], "class_name": "3-Seater", "color_name": "gainsboro"}
22	Tasmania Sofa - Two Seater	sofa_images/sofa_20_LPsML5b.jpg	18867	14527.59	23	1		{"hex_color": "#000000", "rgb_color": [18, 23, 30], "class_name": "2-Seater", "color_name": "black"}
23	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Right Aligned Chaise)	sofa_images/sofa_21_NZVjcdE.jpg	42999	27949.35	35	1		{"hex_color": "#696969", "rgb_color": [98, 91, 87], "class_name": "Sofa-Cum-Bed", "color_name": "dimgray"}
24	Lounger Plus Sofa set (3+2) Seater	sofa_images/sofa_22_fQAEa3B.jpg	72545	52232.4	28	1		{"hex_color": "#2f4f4f", "rgb_color": [24, 39, 48], "class_name": "2-Seater", "color_name": "darkslategray"}
25	Snoozepro Plus L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_23_oBWFXZ7.jpg	47896	34006.16	29	1		{"hex_color": "#808080", "rgb_color": [124, 132, 139], "class_name": "L-Shape", "color_name": "gray"}
26	Brunei Love seat Sofa - 2 Seater	sofa_images/sofa_24_dD9tgiY.jpg	18999	12349.35	35	1		{"hex_color": "#808080", "rgb_color": [116, 120, 122], "class_name": "2-Seater", "color_name": "gray"}
27	Manila Sheesham Wood Sofa - Three Seater	sofa_images/sofa_25_PsHpOVc.jpg	33414	27399.48	18	1		{"hex_color": "#faebd7", "rgb_color": [236, 226, 211], "class_name": "3-Seater", "color_name": "antiquewhite"}
28	Maseru Sofa - Three Seater	sofa_images/sofa_26_tnNpIWE.jpg	27999	18199.35	35	1		{"hex_color": "#f5deb3", "rgb_color": [220, 203, 181], "class_name": "2-Seater", "color_name": "wheat"}
29	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Left Aligned Chaise)	sofa_images/sofa_27_qH7tEMN.jpg	42999	27949.35	35	1		{"hex_color": "#696969", "rgb_color": [90, 88, 91], "class_name": "Sofa-Cum-Bed", "color_name": "dimgray"}
30	Magnus Sofa - Three Seater	sofa_images/sofa_28_HvzHf34.jpg	39999	25999.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [204, 197, 187], "class_name": "2-Seater", "color_name": "silver"}
31	Comoros Corner L Shape Sofa (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_29_yEAbSHG.jpg	84299	54794.35	35	1		{"hex_color": "#808080", "rgb_color": [142, 130, 111], "class_name": "L-Shape", "color_name": "gray"}
32	Lounger Sofa - Three Seater	sofa_images/sofa_30_dvvJgAp.jpg	28499	20234.29	29	1		{"hex_color": "#2f4f4f", "rgb_color": [51, 43, 38], "class_name": "2-Seater", "color_name": "darkslategray"}
33	Hawaii Sofa - 3 Seater - Dark Blue	sofa_images/sofa_31_D4c6FC0.jpg	14399	10655.26	26	1		{"hex_color": "#ffffff", "rgb_color": [254, 254, 254], "class_name": "2-Seater", "color_name": "white"}
34	Napper Mini Sofa - 3 Seater (1.94m*85.09cm*85.34cm) /\n                      (76.5*33.5*33.6inch)	sofa_images/sofa_32_KSsF8yC.jpg	20299	14412.29	29	1		{"hex_color": "#f8f8ff", "rgb_color": [249, 250, 250], "class_name": "3-Seater", "color_name": "ghostwhite"}
35	Dreamer Sofa - Three Seater	sofa_images/sofa_33_gp12bGg.jpg	26880	21235.2	21	1		{"hex_color": "#c0c0c0", "rgb_color": [196, 191, 186], "class_name": "2-Seater", "color_name": "silver"}
36	Bahamas Sheesham Wood Sofa - Three Seater	sofa_images/sofa_34_FLfJebG.jpg	25276	21990.12	13	1		{"hex_color": "#d3d3d3", "rgb_color": [226, 209, 196], "class_name": "2-Seater", "color_name": "lightgray"}
37	Miami Sofa - 3 Seater - Omega Green	sofa_images/sofa_35_vyDbEby.jpg	15200	10336	32	1		{"hex_color": "#696969", "rgb_color": [95, 115, 102], "class_name": "2-Seater", "color_name": "dimgray"}
38	Havana Sofa - Two Seater Cobalt Blue	sofa_images/sofa_36_DeLFr9K.jpg	19500	15210	22	1		{"hex_color": "#f5f5f5", "rgb_color": [241, 241, 241], "class_name": "2-Seater", "color_name": "whitesmoke"}
39	Naples Sofa cum Bed - Three Seater, Omega Blue	sofa_images/sofa_37_nMO0aNW.jpg	14998	11548.46	23	1		{"hex_color": "#808080", "rgb_color": [147, 142, 141], "class_name": "3-Seater", "color_name": "gray"}
40	Fyras 3 Seater Solid wood Sofa	sofa_images/sofa_38_6MK42Ku.jpg	22799	13679.4	40	1		{"hex_color": "#bc8f8f", "rgb_color": [160, 145, 135], "class_name": "2-Seater", "color_name": "rosybrown"}
41	Stefano Sofa - Two Seater	sofa_images/sofa_39_iTxafcW.jpg	32999	19799.4	40	1		{"hex_color": "#2f4f4f", "rgb_color": [81, 68, 60], "class_name": "2-Seater", "color_name": "darkslategray"}
42	Catania 1 Seater Solid wood Sofa	sofa_images/sofa_40_a4X6eji.jpg	16799	10079.4	40	1		{"hex_color": "#dcdcdc", "rgb_color": [230, 221, 213], "class_name": "2-Seater", "color_name": "gainsboro"}
43	Divo 3 Seater Solid wood Sofa	sofa_images/sofa_41_1Er6V8F.jpg	31799	19079.4	40	1		{"hex_color": "#bc8f8f", "rgb_color": [173, 154, 140], "class_name": "3-Seater", "color_name": "rosybrown"}
44	Haverford Sofa - Three Seater	sofa_images/sofa_42_FKBGBUo.jpg	36397	21474.23	41	1		{"hex_color": "#d3d3d3", "rgb_color": [206, 205, 205], "class_name": "2-Seater", "color_name": "lightgray"}
45	Flipper Sofa cum Bed - Three Seater, Omega Blue	sofa_images/sofa_43_c3cmb4Z.jpg	12350	8521.5	31	1		{"hex_color": "#e6e6fa", "rgb_color": [234, 232, 233], "class_name": "2-Seater", "color_name": "lavender"}
46	Solatio Sofa - Three Seater	sofa_images/sofa_44_PpqArBv.jpg	11998	9358.44	22	1		{"hex_color": "#dcdcdc", "rgb_color": [224, 220, 215], "class_name": "2-Seater", "color_name": "gainsboro"}
47	Solomon Sofa Set (3+2) Seater	sofa_images/sofa_45_6dNREoK.jpg	58498	38023.7	35	1		{"hex_color": "#bc8f8f", "rgb_color": [170, 157, 143], "class_name": "2-Seater", "color_name": "rosybrown"}
48	Napper L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_46_WsNswjm.jpg	46279	38874.36	16	1		{"hex_color": "#d3d3d3", "rgb_color": [204, 205, 205], "class_name": "Sofa-Cum-Bed", "color_name": "lightgray"}
49	Amoeba Sofa cum Bed	sofa_images/sofa_47_AGxbWr1.jpg	20900	15048	28	1		{"hex_color": "#808080", "rgb_color": [121, 129, 122], "class_name": "2-Seater", "color_name": "gray"}
50	Barcelona Sofa - Three Seater	sofa_images/sofa_48_7i6W1X7.jpg	30067	26458.96	12	1		{"hex_color": "#2f4f4f", "rgb_color": [32, 57, 89], "class_name": "2-Seater", "color_name": "darkslategray"}
51	Naxos Sofa Set (3+2) Seater	sofa_images/sofa_49_ZmB1DIM.jpg	77997	50698.05	35	1		{"hex_color": "#d3d3d3", "rgb_color": [221, 201, 188], "class_name": "L-Shape", "color_name": "lightgray"}
52	Belize Sofa - Three Seater	sofa_images/sofa_50_xAn8VsD.jpg	23998	20158.32	16	1		{"hex_color": "#f5f5f5", "rgb_color": [241, 246, 249], "class_name": "3-Seater", "color_name": "whitesmoke"}
53	Skiver L Shape 6 Seater Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_51_eDPbmDX.jpg	26000	17680	32	1		{"hex_color": "#c0c0c0", "rgb_color": [200, 198, 195], "class_name": "L-Shape", "color_name": "silver"}
54	Azores Sofa - Two Seater	sofa_images/sofa_52_kqUhI6P.jpg	27999	18199.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [205, 190, 179], "class_name": "2-Seater", "color_name": "silver"}
55	Lumara Sofa -Three Seater	sofa_images/sofa_53_uRZKKtz.jpg	25999	16899.35	35	1		{"hex_color": "#d3d3d3", "rgb_color": [225, 212, 206], "class_name": "3-Seater", "color_name": "lightgray"}
56	Tahiti Sofa - Three Seater	sofa_images/sofa_54_iQop4rb.jpg	37999	24699.35	35	1		{"hex_color": "#a9a9a9", "rgb_color": [186, 167, 156], "class_name": "2-Seater", "color_name": "darkgray"}
57	Belize Plus Sofa - Three Seater	sofa_images/sofa_55_RINIPKm.jpg	32998	25078.48	24	1		{"hex_color": "#a9a9a9", "rgb_color": [160, 163, 155], "class_name": "3-Seater", "color_name": "darkgray"}
58	Dreamer Plus Sofa -Three Seater	sofa_images/sofa_56_RvIEKA3.jpg	35498	26268.52	26	1		{"hex_color": "#ffffff", "rgb_color": [254, 254, 254], "class_name": "2-Seater", "color_name": "white"}
59	Napper Plus Sofa -Three Seater Vogue Deep Ocean	sofa_images/sofa_57_gtV944b.jpg	37167	28618.59	23	1		{"hex_color": "#a9a9a9", "rgb_color": [187, 180, 171], "class_name": "3-Seater", "color_name": "darkgray"}
60	Tuvalu without Motion Sofa Set (3+2) Seater	sofa_images/sofa_58_4HeOB1E.jpg	69498	45173.7	35	1		{"hex_color": "#d3d3d3", "rgb_color": [218, 213, 199], "class_name": "L-Shape", "color_name": "lightgray"}
61	Komodo L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_59_1xkBdgc.jpg	54999	35749.35	35	1		{"hex_color": "#bc8f8f", "rgb_color": [163, 143, 116], "class_name": "L-Shape", "color_name": "rosybrown"}
62	SnoozePro Sofa - Three Seater Omega Green	sofa_images/sofa_60_KYOQqAK.jpg	19600	14504	26	1		{"hex_color": "#696969", "rgb_color": [101, 117, 103], "class_name": "2-Seater", "color_name": "dimgray"}
63	Sicily Sofa - Three Seater	sofa_images/sofa_61_g9CYDfP.jpg	16999	13769.19	19	1		{"hex_color": "#dcdcdc", "rgb_color": [225, 224, 222], "class_name": "3-Seater", "color_name": "gainsboro"}
64	Tasmania Sofa Set - (3+2) Seater	sofa_images/sofa_62_IbYj0ag.jpg	43749	33686.729999999996	23	1		{"hex_color": "#808080", "rgb_color": [127, 116, 107], "class_name": "L-Shape", "color_name": "gray"}
65	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Left Aligned Chaise)	sofa_images/sofa_63_8iKnCtO.jpg	42999	27949.35	35	1		{"hex_color": "#696969", "rgb_color": [93, 95, 84], "class_name": "Sofa-Cum-Bed", "color_name": "dimgray"}
66	Lounger Plus Sofa - (3 Seater +Left Aligned Chaise)	sofa_images/sofa_64_NIBX9Fl.jpg	59123	42568.56	28	1		{"hex_color": "#808080", "rgb_color": [155, 145, 137], "class_name": "L-Shape", "color_name": "gray"}
67	Snoozepro Plus L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_65_nlma00s.jpg	47896	34006.16	29	1		{"hex_color": "#808080", "rgb_color": [124, 132, 140], "class_name": "L-Shape", "color_name": "gray"}
68	Manila Sheesham Wood Sofa - Three Seater	sofa_images/sofa_66_JzPVO8j.jpg	33414	27399.48	18	1		{"hex_color": "#faebd7", "rgb_color": [237, 226, 211], "class_name": "3-Seater", "color_name": "antiquewhite"}
69	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Left Aligned Chaise)	sofa_images/sofa_67_rks9oev.jpg	42999	27949.35	35	1		{"hex_color": "#bc8f8f", "rgb_color": [162, 149, 141], "class_name": "Sofa-Cum-Bed", "color_name": "rosybrown"}
70	Magnus Sofa - Three Seater	sofa_images/sofa_68_QkLL0Aj.jpg	39999	25999.35	35	1		{"hex_color": "#faebd7", "rgb_color": [250, 235, 210], "class_name": "2-Seater", "color_name": "antiquewhite"}
71	Comoros Corner L Shape Sofa (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_69_aipODYz.jpg	84299	54794.35	35	1		{"hex_color": "#808080", "rgb_color": [147, 135, 124], "class_name": "L-Shape", "color_name": "gray"}
72	Lounger L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_70_kcGeNmU.jpg	38208	27127.68	29	1		{"hex_color": "#dcdcdc", "rgb_color": [228, 226, 225], "class_name": "L-Shape", "color_name": "gainsboro"}
73	Haverford Sofa - Two Seater	sofa_images/sofa_71_jsFkhT8.jpg	27899	16739.4	40	1		{"hex_color": "#fffafa", "rgb_color": [252, 251, 250], "class_name": "2-Seater", "color_name": "snow"}
74	Napper Mini Sofa - 3 Seater (1.94m*85.09cm*85.34cm) /\n                      (76.5*33.5*33.6inch)	sofa_images/sofa_72_eJglNmd.jpg	20299	14412.29	29	1		{"hex_color": "#fffafa", "rgb_color": [249, 249, 248], "class_name": "2-Seater", "color_name": "snow"}
75	Dreamer Sofa - Three Seater	sofa_images/sofa_73_JPm0Bik.jpg	25497	20142.63	21	1		{"hex_color": "#696969", "rgb_color": [109, 120, 106], "class_name": "2-Seater", "color_name": "dimgray"}
76	Bahamas Sheesham Wood Sofa Set - (3+2)	sofa_images/sofa_74_C1Q6TNk.jpg	44870	39036.9	13	1		{"hex_color": "#bc8f8f", "rgb_color": [166, 149, 133], "class_name": "2-Seater", "color_name": "rosybrown"}
77	Miami Sofa - 3 Seater - Omega Blue	sofa_images/sofa_75_uavsoyM.jpg	15200	10336	32	1		{"hex_color": "#a9a9a9", "rgb_color": [163, 163, 163], "class_name": "2-Seater", "color_name": "darkgray"}
78	Havana Sofa - Three Seater Malibu Green	sofa_images/sofa_76_HFbZpGd.jpg	26199	20435.22	22	1		{"hex_color": "#d3d3d3", "rgb_color": [203, 207, 212], "class_name": "3-Seater", "color_name": "lightgray"}
79	Naples Sofa cum Bed - Three Seater, Cobalt Blue	sofa_images/sofa_77_0ts3niW.jpg	16170	12612.6	22	1		{"hex_color": "#483d8b", "rgb_color": [83, 61, 103], "class_name": "2-Seater", "color_name": "darkslateblue"}
80	Fyras 2 Seater Solid wood Sofa	sofa_images/sofa_78_6F4t0iY.jpg	18599	11159.4	40	1		{"hex_color": "#d3d3d3", "rgb_color": [215, 214, 215], "class_name": "2-Seater", "color_name": "lightgray"}
81	Solatio Sofa - Three Seater	sofa_images/sofa_79_SOeJ2k8.jpg	11998	9358.44	22	1		{"hex_color": "#000000", "rgb_color": [44, 30, 11], "class_name": "2-Seater", "color_name": "black"}
82	Solomon Sofa - Single Seater	sofa_images/sofa_80_DYdoFjX.jpg	16999	11049.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [199, 198, 189], "class_name": "1-Seater", "color_name": "silver"}
83	Napper Sofa Set (3+2)	sofa_images/sofa_81_7tkLWnf.jpg	47073	38599.86	18	1		{"hex_color": "#f5f5f5", "rgb_color": [248, 248, 248], "class_name": "2-Seater", "color_name": "whitesmoke"}
84	Amoeba Sofa cum Bed	sofa_images/sofa_82_ixCVEVL.jpg	22157	15953.04	28	1		{"hex_color": "#d3d3d3", "rgb_color": [227, 217, 200], "class_name": "2-Seater", "color_name": "lightgray"}
85	Barcelona L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_83_SV3EPpc.jpg	36436	31334.96	14	1		{"hex_color": "#faebd7", "rgb_color": [236, 230, 225], "class_name": "L-Shape", "color_name": "antiquewhite"}
86	Belize L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_84_zhGC3d2.jpg	35130	29860.5	15	1		{"hex_color": "#808080", "rgb_color": [145, 134, 125], "class_name": "L-Shape", "color_name": "gray"}
87	Skiver L Shape 6 Seater Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_85_COMYpCW.jpg	26000	17680	32	1		{"hex_color": "#2f4f4f", "rgb_color": [27, 52, 84], "class_name": "L-Shape", "color_name": "darkslategray"}
88	Azores Sofa Set (3+2+1) Seater	sofa_images/sofa_86_LMQ2NGJ.jpg	80996	52647.4	35	1		{"hex_color": "#c0c0c0", "rgb_color": [190, 185, 178], "class_name": "2-Seater", "color_name": "silver"}
89	Lumara Sofa Set - (3+2) Seater	sofa_images/sofa_87_hySlcDO.jpg	46498	30223.7	35	1		{"hex_color": "#bc8f8f", "rgb_color": [158, 146, 137], "class_name": "L-Shape", "color_name": "rosybrown"}
90	Tahiti Sofa seat(3+2) Seater	sofa_images/sofa_88_TsPXFH8.jpg	69998	45498.7	35	1		{"hex_color": "#8b4513", "rgb_color": [134, 71, 36], "class_name": "L-Shape", "color_name": "saddlebrown"}
91	Belize Plus L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_89_1m4kPCm.jpg	46117	38738.28	16	1		{"hex_color": "#808080", "rgb_color": [139, 116, 99], "class_name": "L-Shape", "color_name": "gray"}
92	Dreamer Plus L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_90_gTMFDHl.jpg	51678	43409.520000000004	16	1		{"hex_color": "#dcdcdc", "rgb_color": [229, 229, 221], "class_name": "L-Shape", "color_name": "gainsboro"}
93	Napper Plus Sofa -Three Seater Reflection Mocha Brown	sofa_images/sofa_91_RGGWMqB.jpg	33998	26178.46	23	1		{"hex_color": "#bc8f8f", "rgb_color": [157, 141, 136], "class_name": "3-Seater", "color_name": "rosybrown"}
94	SnoozePro Sofa Set	sofa_images/sofa_92_cOt4W7X.jpg	36899	27305.260000000002	26	1		{"hex_color": "#f0f8ff", "rgb_color": [240, 246, 252], "class_name": "L-Shape", "color_name": "aliceblue"}
95	Sicily Sofa - Three Seater	sofa_images/sofa_93_fx2gBWF.jpg	16999	13769.19	19	1		{"hex_color": "#dcdcdc", "rgb_color": [227, 226, 223], "class_name": "3-Seater", "color_name": "gainsboro"}
96	Tasmania Sofa Set - (3+2) Seater	sofa_images/sofa_94_KtjQpZJ.jpg	43749	33686.729999999996	23	1		{"hex_color": "#191970", "rgb_color": [18, 38, 73], "class_name": "L-Shape", "color_name": "midnightblue"}
97	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Right Aligned Chaise)	sofa_images/sofa_95_FuZwKoq.jpg	42999	27949.35	35	1		{"hex_color": "#556b2f", "rgb_color": [85, 75, 69], "class_name": "Sofa-Cum-Bed", "color_name": "darkolivegreen"}
98	Lounger Plus Sofa set (3+1+1) Seater	sofa_images/sofa_96_B7MbtNA.jpg	89278	64280.16	28	1		{"hex_color": "#bc8f8f", "rgb_color": [171, 158, 143], "class_name": "L-Shape", "color_name": "rosybrown"}
99	SnoozePro Plus Sofa Set - (3+2+1) Reflection Mocha Brown	sofa_images/sofa_97_gmiIxsd.jpg	62998	44098.6	30	1		{"hex_color": "#c0c0c0", "rgb_color": [192, 191, 183], "class_name": "2-Seater", "color_name": "silver"}
100	Manila Sheesham Wood Sofa Set - (3+2+1)	sofa_images/sofa_98_BGPyvwS.jpg	82242	66616.02	19	1		{"hex_color": "#a9a9a9", "rgb_color": [177, 173, 152], "class_name": "3-Seater", "color_name": "darkgray"}
101	Magnus Sofa Set - (3+2)	sofa_images/sofa_99_og2pxKe.jpg	74998	48748.7	35	1		{"hex_color": "#556b2f", "rgb_color": [113, 78, 55], "class_name": "L-Shape", "color_name": "darkolivegreen"}
102	Comoros Corner L Shape Sofa (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_100_DdEVl67.jpg	80499	52324.35	35	1		{"hex_color": "#808080", "rgb_color": [141, 130, 116], "class_name": "L-Shape", "color_name": "gray"}
103	Lounger Sofa - Three Seater	sofa_images/sofa_101_TPVpwqv.jpg	27585	19585.35	29	1		{"hex_color": "#dcdcdc", "rgb_color": [230, 233, 218], "class_name": "2-Seater", "color_name": "gainsboro"}
104	Haverford Sofa - Single Seater	sofa_images/sofa_102_tBIGfTd.jpg	20097	12058.2	40	1		{"hex_color": "#ffe4e1", "rgb_color": [245, 231, 225], "class_name": "1-Seater", "color_name": "mistyrose"}
105	Napper Mini Sofa - 3 Seater Omega Green	sofa_images/sofa_103_gUSs6Py.jpg	20299	14412.29	29	1		{"hex_color": "#696969", "rgb_color": [109, 124, 115], "class_name": "3-Seater", "color_name": "dimgray"}
106	Dreamer Sofa Set (3+2)	sofa_images/sofa_104_Wlgq2d0.jpg	48238	37625.64	22	1		{"hex_color": "#c0c0c0", "rgb_color": [196, 191, 186], "class_name": "2-Seater", "color_name": "silver"}
107	Bahamas Sheesham Wood Sofa Set - (3+2)	sofa_images/sofa_105_Lbks1wM.jpg	45684	39745.08	13	1		{"hex_color": "#bc8f8f", "rgb_color": [166, 148, 133], "class_name": "2-Seater", "color_name": "rosybrown"}
108	Miami Sofa - 3 Seater - Omega Pearl	sofa_images/sofa_106_XkQyHEU.jpg	15200	10336	32	1		{"hex_color": "#a9a9a9", "rgb_color": [170, 163, 160], "class_name": "2-Seater", "color_name": "darkgray"}
109	Havana Sofa - Three Seater Cobalt Blue	sofa_images/sofa_107_DUNMdkg.jpg	26199	20435.22	22	1		{"hex_color": "#d3d3d3", "rgb_color": [226, 208, 195], "class_name": "3-Seater", "color_name": "lightgray"}
110	Naples Sofa cum Bed - Three Seater, Omega Pearl	sofa_images/sofa_108_rvXkLcU.jpg	14998	11548.46	23	1		{"hex_color": "#a9a9a9", "rgb_color": [165, 159, 149], "class_name": "2-Seater", "color_name": "darkgray"}
111	Fyras 1 Seater Solid wood Sofa	sofa_images/sofa_109_an1prZf.jpg	13619	8171.4	40	1		{"hex_color": "#bc8f8f", "rgb_color": [174, 144, 122], "class_name": "1-Seater", "color_name": "rosybrown"}
112	Solomon Sofa Set (3+2+1) Seater	sofa_images/sofa_110_b58D9qZ.jpg	75497	49073.05	35	1		{"hex_color": "#c0c0c0", "rgb_color": [201, 194, 183], "class_name": "L-Shape", "color_name": "silver"}
113	Napper Sofa Set - Three Seater	sofa_images/sofa_111_unGzRoX.jpg	25000	21000	16	1		{"hex_color": "#696969", "rgb_color": [109, 124, 115], "class_name": "3-Seater", "color_name": "dimgray"}
114	Amoeba Sofa cum Bed	sofa_images/sofa_112_00gYYXy.jpg	22157	15953.04	28	1		{"hex_color": "#2f4f4f", "rgb_color": [51, 51, 51], "class_name": "2-Seater", "color_name": "darkslategray"}
115	Barcelona Sofa - Three Seater	sofa_images/sofa_113_t2iul9X.jpg	27300	24024	12	1		{"hex_color": "#808080", "rgb_color": [126, 139, 130], "class_name": "3-Seater", "color_name": "gray"}
116	Belize L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_114_jvqyhGz.jpg	34898	29663.3	15	1		{"hex_color": "#2f4f4f", "rgb_color": [30, 49, 72], "class_name": "L-Shape", "color_name": "darkslategray"}
117	Skiver L Shape 6 Seater Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_115_iFKBnyU.jpg	26000	17680	32	1		{"hex_color": "#2f4f4f", "rgb_color": [41, 39, 52], "class_name": "L-Shape", "color_name": "darkslategray"}
118	Azores Sofa Set (3+2) Seater	sofa_images/sofa_116_t2WpzzV.jpg	61998	40298.7	35	1		{"hex_color": "#a9a9a9", "rgb_color": [175, 169, 163], "class_name": "2-Seater", "color_name": "darkgray"}
119	Lumara Sofa Set - (3+1+1) Seater	sofa_images/sofa_117_o9klYaW.jpg	55996	36397.4	35	1		{"hex_color": "#808080", "rgb_color": [150, 138, 129], "class_name": "L-Shape", "color_name": "gray"}
120	Tahiti Sofa seat(3+2) Seater	sofa_images/sofa_118_BJ3RxhR.jpg	69998	45498.7	35	1		{"hex_color": "#d3d3d3", "rgb_color": [219, 210, 200], "class_name": "L-Shape", "color_name": "lightgray"}
121	Belize Plus Sofa Set - (3+2)	sofa_images/sofa_119_1K2ggyW.jpg	55676	41757	25	1		{"hex_color": "#bc8f8f", "rgb_color": [175, 162, 147], "class_name": "L-Shape", "color_name": "rosybrown"}
122	Dreamer Plus Sofa Set - (3+2)	sofa_images/sofa_120_K2ldC9c.jpg	61973	45860.020000000004	26	1		{"hex_color": "#5f9ea0", "rgb_color": [119, 156, 174], "class_name": "L-Shape", "color_name": "cadetblue"}
123	Napper Plus Sofa Set - (3+2) Reflection Rose Brown	sofa_images/sofa_121_n4HKOrJ.jpg	59692	45962.84	23	1		{"hex_color": "#808080", "rgb_color": [162, 121, 123], "class_name": "L-Shape", "color_name": "gray"}
124	SnoozePro Sofa Set (3+2)	sofa_images/sofa_122_Stb9QNO.jpg	34397	25109.809999999998	27	1		{"hex_color": "#faf0e6", "rgb_color": [240, 238, 229], "class_name": "3-Seater", "color_name": "linen"}
125	Sicily Sofa - Three Seater	sofa_images/sofa_123_UyhjvSc.jpg	17839	14449.59	19	1		{"hex_color": "#696969", "rgb_color": [83, 83, 95], "class_name": "2-Seater", "color_name": "dimgray"}
126	Tasmania Sofa - Two Seater	sofa_images/sofa_124_vgX5YAD.jpg	18867	14527.59	23	1		{"hex_color": "#000000", "rgb_color": [24, 24, 27], "class_name": "2-Seater", "color_name": "black"}
127	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Right Aligned Chaise)	sofa_images/sofa_125_8W5xlqk.jpg	42999	27949.35	35	1		{"hex_color": "#696969", "rgb_color": [90, 87, 91], "class_name": "Sofa-Cum-Bed", "color_name": "dimgray"}
128	Lounger Plus Sofa set (3+2) Seater	sofa_images/sofa_126_guhu3ao.jpg	67234	48408.479999999996	28	1		{"hex_color": "#696969", "rgb_color": [117, 82, 76], "class_name": "L-Shape", "color_name": "dimgray"}
129	SnoozePro Plus Sofa -Two Seater Reflection Rose Brown	sofa_images/sofa_127_xuYJAQK.jpg	20999	14699.3	30	1		{"hex_color": "#696969", "rgb_color": [137, 94, 101], "class_name": "2-Seater", "color_name": "dimgray"}
130	Manila Sheesham Wood Sofa Set - (3+2)	sofa_images/sofa_128_HCG0LeO.jpg	63145	51147.45	19	1		{"hex_color": "#faebd7", "rgb_color": [236, 226, 211], "class_name": "3-Seater", "color_name": "antiquewhite"}
131	Magnus Sofa Set - (3+2)	sofa_images/sofa_129_oSJaM74.jpg	74998	48748.7	35	1		{"hex_color": "#bc8f8f", "rgb_color": [182, 159, 131], "class_name": "L-Shape", "color_name": "rosybrown"}
132	Comoros Corner L Shape Sofa (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_130_KVXBfKy.jpg	80499	52324.35	35	1		{"hex_color": "#808080", "rgb_color": [137, 128, 108], "class_name": "L-Shape", "color_name": "gray"}
159	Lounger Sofa - Single Seater	sofa_images/sofa_157_wOWbeKB.jpg	18081	12656.7	30	1		{"hex_color": "#a9a9a9", "rgb_color": [173, 162, 150], "class_name": "2-Seater", "color_name": "darkgray"}
133	Lounger L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_131_eSv5aOY.jpg	38208	27127.68	29	1		{"hex_color": "#dcdcdc", "rgb_color": [228, 226, 225], "class_name": "L-Shape", "color_name": "gainsboro"}
134	Napper Mini Sofa - 3 Seater (1.94m*85.09cm*85.34cm) /\n                      (76.5*33.5*33.6inch)	sofa_images/sofa_132_7exA7vg.jpg	20299	14412.29	29	1		{"hex_color": "#f5f5f5", "rgb_color": [248, 248, 248], "class_name": "2-Seater", "color_name": "whitesmoke"}
135	Dreamer L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_133_6yRgnOn.jpg	35277	27868.83	21	1		{"hex_color": "#a9a9a9", "rgb_color": [177, 179, 174], "class_name": "L-Shape", "color_name": "darkgray"}
136	Bahamas Sheesham Wood Sofa - Two Seater	sofa_images/sofa_134_XWihhdQ.jpg	19594	17046.78	13	1		{"hex_color": "#d3d3d3", "rgb_color": [224, 216, 205], "class_name": "2-Seater", "color_name": "lightgray"}
137	Miami Sofa - 3+2 Seater - Omega Blue	sofa_images/sofa_135_Jl8P2wH.jpg	27999	19039.32	32	1		{"hex_color": "#a9a9a9", "rgb_color": [163, 163, 163], "class_name": "2-Seater", "color_name": "darkgray"}
138	Havana Sofa Set (3+2) Reflection Green	sofa_images/sofa_136_xZZw6Q8.jpg	49697	38763.66	22	1		{"hex_color": "#556b2f", "rgb_color": [99, 97, 71], "class_name": "L-Shape", "color_name": "darkolivegreen"}
139	Naples Sofa cum Bed - Three Seater, Omega Ash Grey	sofa_images/sofa_137_Gur7vJn.jpg	14998	11548.46	23	1		{"hex_color": "#2f4f4f", "rgb_color": [69, 69, 69], "class_name": "3-Seater", "color_name": "darkslategray"}
140	Lounger Plus Sofa -Three Seater	sofa_images/sofa_138_fwjlE3x.jpg	40310	29023.2	28	1		{"hex_color": "#bc8f8f", "rgb_color": [167, 155, 142], "class_name": "Sofa-Cum-Bed", "color_name": "rosybrown"}
141	Napper Storage L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_139_z8nC4rB.jpg	46173	33706.29	27	1		{"hex_color": "#a9a9a9", "rgb_color": [160, 154, 150], "class_name": "L-Shape", "color_name": "darkgray"}
142	Tasmania Sofa - Two Seater	sofa_images/sofa_140_NEAnSD1.jpg	18867	14527.59	23	1		{"hex_color": "#000000", "rgb_color": [22, 23, 26], "class_name": "2-Seater", "color_name": "black"}
143	Napper Storage L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_141_7Ahm8vc.jpg	46173	33706.29	27	1		{"hex_color": "#696969", "rgb_color": [100, 115, 100], "class_name": "L-Shape", "color_name": "dimgray"}
144	Flipper Sofa cum Bed - Three Seater, Omega Ash Grey	sofa_images/sofa_142_bSuKYY0.jpg	12350	8521.5	31	1		{"hex_color": "#2f4f4f", "rgb_color": [54, 50, 46], "class_name": "3-Seater", "color_name": "darkslategray"}
145	Tasmania Sofa - Three Seater	sofa_images/sofa_143_JGMQWfj.jpg	25001	19250.77	23	1		{"hex_color": "#000000", "rgb_color": [32, 35, 38], "class_name": "2-Seater", "color_name": "black"}
146	Napper Sofa - Single Seater	sofa_images/sofa_144_biJfNJO.jpg	14526	12056.58	17	1		{"hex_color": "#f8f8ff", "rgb_color": [249, 250, 250], "class_name": "3-Seater", "color_name": "ghostwhite"}
147	Napper Ottoman	sofa_images/sofa_145_ipHTaoB.jpg	6305	5107.05	19	1		{"hex_color": "#808080", "rgb_color": [117, 120, 127], "class_name": "1-Seater", "color_name": "gray"}
148	Napper L Shape Sofa Set (3 Seater + Left Aligned Chaise)	sofa_images/sofa_146_7dvBpoQ.jpg	41665	34581.95	17	1		{"hex_color": "#a9a9a9", "rgb_color": [153, 165, 175], "class_name": "L-Shape", "color_name": "darkgray"}
149	Napper L Shape Sofa Set (3 Seater + Left Aligned Chaise\n                      with Ottoman)	sofa_images/sofa_147_elCqoOi.jpg	46733	37853.729999999996	19	1		{"hex_color": "#dcdcdc", "rgb_color": [229, 230, 228], "class_name": "Sofa-Cum-Bed", "color_name": "gainsboro"}
150	Napper Sofa - Three Seater	sofa_images/sofa_148_vnLetVP.jpg	25000	21000	16	1		{"hex_color": "#f5f5f5", "rgb_color": [248, 248, 248], "class_name": "2-Seater", "color_name": "whitesmoke"}
151	Napper Ottoman	sofa_images/sofa_149_GdDM2kO.jpg	6305	5107.05	19	1		{"hex_color": "#a9a9a9", "rgb_color": [182, 167, 155], "class_name": "1-Seater", "color_name": "darkgray"}
152	SnoozePro Sofa - Single Seater	sofa_images/sofa_150_v5ihlys.jpg	13799	10073.27	27	1		{"hex_color": "#faf0e6", "rgb_color": [240, 235, 228], "class_name": "3-Seater", "color_name": "linen"}
153	SnoozePro Ottoman	sofa_images/sofa_151_qpWG4gV.jpg	5897	4245.84	28	1		{"hex_color": "#808080", "rgb_color": [117, 120, 127], "class_name": "1-Seater", "color_name": "gray"}
154	SnoozePro L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_152_ACpg2K9.jpg	33800	25012	26	1		{"hex_color": "#fffafa", "rgb_color": [254, 250, 250], "class_name": "L-Shape", "color_name": "snow"}
155	SnoozePro Sofa - Two Seater	sofa_images/sofa_153_gc7u2YD.jpg	15199	11095.27	27	1		{"hex_color": "#808080", "rgb_color": [160, 137, 116], "class_name": "2-Seater", "color_name": "gray"}
156	SnoozePro L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_154_6EZwdtS.jpg	33800	25012	26	1		{"hex_color": "#fffafa", "rgb_color": [250, 250, 250], "class_name": "L-Shape", "color_name": "snow"}
157	SnoozePro Sofa - Two Seater	sofa_images/sofa_155_4G7VMCw.jpg	15199	11095.27	27	1		{"hex_color": "#faf0e6", "rgb_color": [240, 236, 228], "class_name": "3-Seater", "color_name": "linen"}
158	SnoozePro Sofa - Three Seater	sofa_images/sofa_156_D04tT8M.jpg	19600	14504	26	1		{"hex_color": "#faf0e6", "rgb_color": [240, 236, 228], "class_name": "3-Seater", "color_name": "linen"}
160	Lounger Sofa - Two Seater	sofa_images/sofa_158_1NMpHQB.jpg	24315	16777.35	31	1		{"hex_color": "#a9a9a9", "rgb_color": [173, 162, 150], "class_name": "2-Seater", "color_name": "darkgray"}
161	Lounger Sofa - Three Seater	sofa_images/sofa_159_9jv9i5K.jpg	30646	21758.66	29	1		{"hex_color": "#a9a9a9", "rgb_color": [173, 162, 150], "class_name": "2-Seater", "color_name": "darkgray"}
162	SnoozePro Sofa - Three Seater	sofa_images/sofa_160_DiODrcG.jpg	21399	15835.26	26	1		{"hex_color": "#f5f5dc", "rgb_color": [237, 234, 224], "class_name": "3-Seater", "color_name": "beige"}
163	Napper Sofa - Single Seater	sofa_images/sofa_161_cTkh6hq.jpg	14189	11776.869999999999	17	1		{"hex_color": "#ffffff", "rgb_color": [254, 254, 254], "class_name": "3-Seater", "color_name": "white"}
164	Napper Sofa - Two Seater	sofa_images/sofa_162_4d5IPML.jpg	21057	17477.31	17	1		{"hex_color": "#ffffff", "rgb_color": [254, 254, 254], "class_name": "3-Seater", "color_name": "white"}
165	Napper Sofa - Three Seater	sofa_images/sofa_163_sxQ8pdP.jpg	27814	23363.760000000002	16	1		{"hex_color": "#f8f8ff", "rgb_color": [248, 249, 250], "class_name": "3-Seater", "color_name": "ghostwhite"}
166	Napper Sofa - Three Seater	sofa_images/sofa_164_6fSFiaf.jpg	27814	23363.760000000002	16	1		{"hex_color": "#ffffff", "rgb_color": [254, 254, 254], "class_name": "3-Seater", "color_name": "white"}
167	Stargazer Rocking & Revolving Recliner - 1 Seater -\n                      Amber	sofa_images/sofa_165_w1qYaWD.jpg	22500	16875	25	1		{"hex_color": "#a0522d", "rgb_color": [159, 86, 44], "class_name": "1-Seater", "color_name": "sienna"}
168	SnoozePro Ottoman	sofa_images/sofa_166_WaO9Cqt.jpg	6599	4751.28	28	1		{"hex_color": "#ffffff", "rgb_color": [255, 255, 255], "class_name": "1-Seater", "color_name": "white"}
169	Napper Ottoman	sofa_images/sofa_167_gg6uZXv.jpg	7094	5746.14	19	1		{"hex_color": "#ffffff", "rgb_color": [255, 255, 255], "class_name": "1-Seater", "color_name": "white"}
170	Napper Ottoman	sofa_images/sofa_168_WKSocYF.jpg	7094	5746.14	19	1		{"hex_color": "#ffffff", "rgb_color": [255, 255, 255], "class_name": "1-Seater", "color_name": "white"}
171	Napper L Shape Sofa Set (3 Seater + Left Aligned Chaise)	sofa_images/sofa_169_VR70R8h.jpg	46279	38874.36	16	1		{"hex_color": "#d3d3d3", "rgb_color": [204, 205, 205], "class_name": "Sofa-Cum-Bed", "color_name": "lightgray"}
172	Lounger Sofa - Two Seater	sofa_images/sofa_170_IW3alRH.jpg	21758	15230.6	30	1		{"hex_color": "#dcdcdc", "rgb_color": [230, 233, 218], "class_name": "2-Seater", "color_name": "gainsboro"}
173	Lounger Sofa Set (3+2+1)	sofa_images/sofa_171_hi6aVYf.jpg	64874	45411.8	30	1		{"hex_color": "#dcdcdc", "rgb_color": [229, 233, 217], "class_name": "2-Seater", "color_name": "gainsboro"}
174	Lounger Sofa - Three Seater	sofa_images/sofa_172_6wnh61V.jpg	27585	19585.35	29	1		{"hex_color": "#dcdcdc", "rgb_color": [230, 233, 217], "class_name": "2-Seater", "color_name": "gainsboro"}
175	Lounger Sofa - Two Seater	sofa_images/sofa_173_Z3nTgmT.jpg	22577	15578.130000000001	31	1		{"hex_color": "#f5f5dc", "rgb_color": [231, 234, 222], "class_name": "2-Seater", "color_name": "beige"}
176	Lounger Sofa - Three Seater	sofa_images/sofa_174_0QD78B9.jpg	28499	20234.29	29	1		{"hex_color": "#f5f5dc", "rgb_color": [231, 234, 222], "class_name": "2-Seater", "color_name": "beige"}
177	Lounger Sofa Set (3+2)	sofa_images/sofa_175_DnVVnPJ.jpg	50567	34891.229999999996	31	1		{"hex_color": "#f5f5dc", "rgb_color": [231, 234, 222], "class_name": "2-Seater", "color_name": "beige"}
178	Lounger Sofa - Two Seater	sofa_images/sofa_176_67XgrfF.jpg	22577	15578.130000000001	31	1		{"hex_color": "#a9a9a9", "rgb_color": [185, 181, 171], "class_name": "2-Seater", "color_name": "darkgray"}
179	Lounger Sofa Set (3+2)	sofa_images/sofa_177_L0XBfpc.jpg	50567	34891.229999999996	31	1		{"hex_color": "#a9a9a9", "rgb_color": [185, 182, 171], "class_name": "2-Seater", "color_name": "darkgray"}
180	Stargazer Recliner - 1 Seater - Amber	sofa_images/sofa_178_i2xmJZF.jpg	18500	13690	26	1		{"hex_color": "#deb887", "rgb_color": [225, 179, 142], "class_name": "1-Seater", "color_name": "burlywood"}
181	Amoeba Sofa cum Bed	sofa_images/sofa_179_vCiNhF3.jpg	20900	15048	28	1		{"hex_color": "#808080", "rgb_color": [150, 147, 133], "class_name": "1-Seater", "color_name": "gray"}
182	Amoeba Sofa cum Bed	sofa_images/sofa_180_4Jg4VlU.jpg	20900	15048	28	1		{"hex_color": "#a9a9a9", "rgb_color": [171, 162, 151], "class_name": "2-Seater", "color_name": "darkgray"}
183	Amoeba Sofa cum Bed	sofa_images/sofa_181_HObnrwX.jpg	20900	15048	28	1		{"hex_color": "#2f4f4f", "rgb_color": [79, 74, 68], "class_name": "2-Seater", "color_name": "darkslategray"}
184	Dreamer Sofa - Single Seater	sofa_images/sofa_182_rOvNxet.jpg	15830	12347.4	22	1		{"hex_color": "#2f4f4f", "rgb_color": [18, 91, 99], "class_name": "1-Seater", "color_name": "darkslategray"}
185	Dreamer Sofa - Two Seater	sofa_images/sofa_183_IO2LBhV.jpg	18381	14337.18	22	1		{"hex_color": "#a9a9a9", "rgb_color": [174, 166, 158], "class_name": "2-Seater", "color_name": "darkgray"}
186	Dreamer Sofa - Three Seater	sofa_images/sofa_184_vbDVJLN.jpg	25497	20142.63	21	1		{"hex_color": "#a9a9a9", "rgb_color": [168, 161, 152], "class_name": "2-Seater", "color_name": "darkgray"}
187	Dreamer Sofa - Three Seater	sofa_images/sofa_185_jhfqzzz.jpg	25497	20142.63	21	1		{"hex_color": "#696969", "rgb_color": [107, 106, 100], "class_name": "2-Seater", "color_name": "dimgray"}
188	Amoeba Sofa cum Bed	sofa_images/sofa_186_16bzItg.jpg	20900	15048	28	1		{"hex_color": "#a52a2a", "rgb_color": [182, 55, 58], "class_name": "2-Seater", "color_name": "brown"}
189	Miami Sofa - 1 Seater - Omega Blue	sofa_images/sofa_187_eAX9NRN.jpg	9999	6899.3099999999995	31	1		{"hex_color": "#a9a9a9", "rgb_color": [163, 163, 163], "class_name": "2-Seater", "color_name": "darkgray"}
190	Miami Sofa - 3+2+1 Seater - Omega Blue	sofa_images/sofa_188_jIuVS53.jpg	37897	25769.96	32	1		{"hex_color": "#a9a9a9", "rgb_color": [163, 163, 163], "class_name": "2-Seater", "color_name": "darkgray"}
191	Miami Sofa - 3 Seater - Omega Grey	sofa_images/sofa_189_FYtzkSX.jpg	15200	10336	32	1		{"hex_color": "#696969", "rgb_color": [89, 88, 84], "class_name": "2-Seater", "color_name": "dimgray"}
192	Miami Sofa - 2 Seater - Chrome Yellow	sofa_images/sofa_190_MLepQPi.jpg	14599	9927.32	32	1		{"hex_color": "#daa520", "rgb_color": [220, 153, 2], "class_name": "2-Seater", "color_name": "goldenrod"}
193	Miami Sofa - 3 Seater - Chrome Yellow	sofa_images/sofa_191_OfdQY7O.jpg	17197	11693.96	32	1		{"hex_color": "#daa520", "rgb_color": [220, 154, 2], "class_name": "2-Seater", "color_name": "goldenrod"}
194	Miami Sofa - 3 Seater - Ash Grey	sofa_images/sofa_192_pWcZqAT.jpg	17197	11693.96	32	1		{"hex_color": "#2f4f4f", "rgb_color": [75, 76, 73], "class_name": "2-Seater", "color_name": "darkslategray"}
195	Dreamer Sofa Set (3+2+1)	sofa_images/sofa_193_JcLO8rC.jpg	65770	51300.6	22	1		{"hex_color": "#20b2aa", "rgb_color": [57, 183, 177], "class_name": "L-Shape", "color_name": "lightseagreen"}
196	Stargazer Recliner - 1 Seater - Dark Fantasy	sofa_images/sofa_194_t2hlAJU.jpg	18500	13690	26	1		{"hex_color": "#2f4f4f", "rgb_color": [68, 53, 48], "class_name": "1-Seater", "color_name": "darkslategray"}
197	Hawaii Sofa - 3 Seater - Sky Green	sofa_images/sofa_195_ukuwnRB.jpg	14399	10655.26	26	1		{"hex_color": "#ffffff", "rgb_color": [254, 254, 254], "class_name": "2-Seater", "color_name": "white"}
198	Stargazer Recliner - Rocking & Revolving	sofa_images/sofa_196_UjH1y3w.jpg	22500	16875	25	1		{"hex_color": "#696969", "rgb_color": [102, 81, 74], "class_name": "1-Seater", "color_name": "dimgray"}
199	Muser Recliner - Electric	sofa_images/sofa_197_AbnQiZ4.jpg	25001	13500.54	46	1		{"hex_color": "#a9a9a9", "rgb_color": [169, 168, 154], "class_name": "1-Seater", "color_name": "darkgray"}
200	Stargazer Recliner - 1 Seater - Marble Grey	sofa_images/sofa_198_auMZHkm.jpg	18500	13690	26	1		{"hex_color": "#2f4f4f", "rgb_color": [62, 62, 62], "class_name": "1-Seater", "color_name": "darkslategray"}
201	Stargazer Recliner - 1 Seater - Sangria	sofa_images/sofa_199_kUS5Pew.jpg	18500	13690	26	1		{"hex_color": "#2f4f4f", "rgb_color": [79, 43, 44], "class_name": "1-Seater", "color_name": "darkslategray"}
202	Stargazer Recliner - 1 Seater - Tan	sofa_images/sofa_200_6j2ZBhV.jpg	18500	13690	26	1		{"hex_color": "#8b4513", "rgb_color": [128, 59, 43], "class_name": "1-Seater", "color_name": "saddlebrown"}
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-01-16 17:21:12.739987+05:30	2	Solatio Sofa - Three Seater	3		7	1
2	2025-01-16 17:21:12.745213+05:30	1	Flipper Sofa Cum Bed - Three Seater (6'x5') Feet- WarpKnit\n                      Grey	3		7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	couch_management	sofa
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-01-16 16:48:13.690424+05:30
2	auth	0001_initial	2025-01-16 16:48:13.770333+05:30
3	admin	0001_initial	2025-01-16 16:48:13.792401+05:30
4	admin	0002_logentry_remove_auto_add	2025-01-16 16:48:13.798717+05:30
5	admin	0003_logentry_add_action_flag_choices	2025-01-16 16:48:13.803884+05:30
6	contenttypes	0002_remove_content_type_name	2025-01-16 16:48:13.813124+05:30
7	auth	0002_alter_permission_name_max_length	2025-01-16 16:48:13.820036+05:30
8	auth	0003_alter_user_email_max_length	2025-01-16 16:48:13.825175+05:30
9	auth	0004_alter_user_username_opts	2025-01-16 16:48:13.830514+05:30
10	auth	0005_alter_user_last_login_null	2025-01-16 16:48:13.835949+05:30
11	auth	0006_require_contenttypes_0002	2025-01-16 16:48:13.838405+05:30
12	auth	0007_alter_validators_add_error_messages	2025-01-16 16:48:13.84347+05:30
13	auth	0008_alter_user_username_max_length	2025-01-16 16:48:13.851026+05:30
14	auth	0009_alter_user_last_name_max_length	2025-01-16 16:48:13.85633+05:30
15	auth	0010_alter_group_name_max_length	2025-01-16 16:48:13.861948+05:30
16	auth	0011_update_proxy_permissions	2025-01-16 16:48:13.867089+05:30
17	auth	0012_alter_user_first_name_max_length	2025-01-16 16:48:13.872418+05:30
18	couch_management	0001_initial	2025-01-16 16:48:13.878878+05:30
19	sessions	0001_initial	2025-01-16 16:48:13.888816+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
5vqszi1ghkbwgmuhc9ps8cmkcwzbyq3l	.eJxVjDsOAjEMBe-SGkXki0NJzxlWtuOQBZRI-6kQd4eVtoD2zcx7qQHXpQ7rLNMwZnVWRh1-N0J-SNtAvmO7dc29LdNIelP0Tmd97Vmel939O6g412-dXOGUKBcb0Tk8AXiTJLpQ0IulIJyD8RKBCY5iLVhmCECuGAZCr94f7ms4Qw:1tYNxl:nmq1T2TEXh6IEceqw6b-0Io2g29222K7bgwwUsDWPK4	2025-01-30 16:53:01.666863+05:30
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 28, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: couch_management_sofa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.couch_management_sofa_id_seq', 202, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 2, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 7, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: couch_management_sofa couch_management_sofa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.couch_management_sofa
    ADD CONSTRAINT couch_management_sofa_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

