--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-1.pgdg20.04+1)
-- Dumped by pg_dump version 17.2 (Ubuntu 17.2-1.pgdg20.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: couch_management_sofa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.couch_management_sofa (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    image character varying(100) NOT NULL,
    price double precision NOT NULL,
    original_price double precision NOT NULL,
    discount double precision NOT NULL,
    quantity integer NOT NULL,
    description text,
    features jsonb
);


ALTER TABLE public.couch_management_sofa OWNER TO postgres;

--
-- Name: couch_management_sofa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.couch_management_sofa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.couch_management_sofa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add sofa	7	add_sofa
26	Can change sofa	7	change_sofa
27	Can delete sofa	7	delete_sofa
28	Can view sofa	7	view_sofa
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$hJbfUJC3tM671tqsEgjqvb$V10apdYnll3jBHakmECJD02oYTC1aoVZoXeAbhJd548=	2025-01-16 16:53:01.664503+05:30	t	admin				t	t	2025-01-16 16:52:01.093317+05:30
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: couch_management_sofa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.couch_management_sofa (id, name, image, price, original_price, discount, quantity, description, features) FROM stdin;
27	Manila Sheesham Wood Sofa - Three Seater	sofa_images/sofa_25.jpg	33414	27399.48	18	1		{"hex_color": "#556b2f", "rgb_color": [90, 91, 60], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
28	Maseru Sofa - Three Seater	sofa_images/sofa_26.jpg	27999	18199.35	35	1		{"hex_color": "#f5deb3", "rgb_color": [230, 212, 191], "sofa_type": "3-Seater", "color_name": "wheat"}
7	Amoeba Sofa cum Bed	sofa_images/sofa_5.jpg	22157	15953.04	28	1		{"hex_color": "#2f4f4f", "rgb_color": [42, 63, 96], "sofa_type": "2-Seater", "color_name": "darkslategray"}
8	Barcelona L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_6.jpg	40407	35558.16	12	1		{"hex_color": "#000000", "rgb_color": [25, 24, 21], "sofa_type": "L-Shape", "color_name": "black"}
10	Belize L Shape Sofa Set (3 Seater + Left Aligned Chaise)	sofa_images/sofa_8.jpg	32694	27789.9	15	1		{"hex_color": "#2f4f4f", "rgb_color": [68, 75, 85], "sofa_type": "L-Shape", "color_name": "darkslategray"}
22	Tasmania Sofa - Two Seater	sofa_images/sofa_20.jpg	18867	14527.59	23	1		{"hex_color": "#000000", "rgb_color": [6, 19, 35], "sofa_type": "2-Seater", "color_name": "black"}
24	Lounger Plus Sofa set (3+2) Seater	sofa_images/sofa_22.jpg	72545	52232.4	28	1		{"hex_color": "#2f4f4f", "rgb_color": [28, 44, 54], "sofa_type": "2-Seater", "color_name": "darkslategray"}
25	Snoozepro Plus L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_23.jpg	47896	34006.16	29	1		{"hex_color": "#696969", "rgb_color": [108, 119, 114], "sofa_type": "L-Shape", "color_name": "dimgray"}
26	Brunei Love seat Sofa - 2 Seater	sofa_images/sofa_24.jpg	18999	12349.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [199, 201, 202], "sofa_type": "2-Seater", "color_name": "silver"}
3	Flipper Sofa Cum Bed - Three Seater (6'x5') Feet- WarpKnit\n                      Grey	sofa_images/sofa_1.jpg	8999	6209.3099999999995	31	1		{"hex_color": "#2f4f4f", "rgb_color": [67, 65, 63], "sofa_type": "3-Seater", "color_name": "darkslategray"}
4	Solatio Sofa - Three Seater	sofa_images/sofa_2.jpg	11998	9358.44	22	1		{"hex_color": "#191970", "rgb_color": [21, 47, 80], "sofa_type": "3-Seater", "color_name": "midnightblue"}
5	Solomon Sofa - Three Seater	sofa_images/sofa_3.jpg	32999	21449.35	35	1		{"hex_color": "#a9a9a9", "rgb_color": [193, 182, 163], "sofa_type": "3-Seater", "color_name": "darkgray"}
6	Napper Sofa - Three Seater	sofa_images/sofa_4.jpg	25000	21000	16	1		{"hex_color": "#000000", "rgb_color": [22, 19, 18], "sofa_type": "3-Seater", "color_name": "black"}
38	Havana Sofa - Two Seater Cobalt Blue	sofa_images/sofa_36.jpg	19500	15210	22	1		{"hex_color": "#2f4f4f", "rgb_color": [38, 56, 77], "sofa_type": "3-Seater", "color_name": "darkslategray"}
39	Naples Sofa cum Bed - Three Seater, Omega Blue	sofa_images/sofa_37.jpg	14998	11548.46	23	1		{"hex_color": "#696969", "rgb_color": [103, 111, 126], "sofa_type": "3-Seater", "color_name": "dimgray"}
40	Fyras 3 Seater Solid wood Sofa	sofa_images/sofa_38.jpg	22799	13679.4	40	1		{"hex_color": "#2f4f4f", "rgb_color": [82, 72, 66], "sofa_type": "3-Seater", "color_name": "darkslategray"}
43	Divo 3 Seater Solid wood Sofa	sofa_images/sofa_41.jpg	31799	19079.4	40	1		{"hex_color": "#c0c0c0", "rgb_color": [197, 181, 170], "sofa_type": "3-Seater", "color_name": "silver"}
44	Haverford Sofa - Three Seater	sofa_images/sofa_42.jpg	36397	21474.23	41	1		{"hex_color": "#000000", "rgb_color": [25, 31, 40], "sofa_type": "3-Seater", "color_name": "black"}
47	Solomon Sofa Set (3+2) Seater	sofa_images/sofa_45.jpg	58498	38023.7	35	1		{"hex_color": "#8b4513", "rgb_color": [122, 62, 33], "sofa_type": "3-Seater", "color_name": "saddlebrown"}
41	Stefano Sofa - Two Seater	sofa_images/sofa_39.jpg	32999	19799.4	40	1		{"hex_color": "#2f4f4f", "rgb_color": [80, 68, 62], "sofa_type": "2-Seater", "color_name": "darkslategray"}
42	Catania 1 Seater Solid wood Sofa	sofa_images/sofa_40.jpg	16799	10079.4	40	1		{"hex_color": "#008080", "rgb_color": [34, 120, 128], "sofa_type": "1-Seater", "color_name": "teal"}
49	Amoeba Sofa cum Bed	sofa_images/sofa_47.jpg	20900	15048	28	1		{"hex_color": "#808080", "rgb_color": [120, 128, 121], "sofa_type": "2-Seater", "color_name": "gray"}
53	Skiver L Shape 6 Seater Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_51.jpg	26000	17680	32	1		{"hex_color": "#000000", "rgb_color": [35, 27, 21], "sofa_type": "L-Shape", "color_name": "black"}
54	Azores Sofa - Two Seater	sofa_images/sofa_52.jpg	27999	18199.35	35	1		{"hex_color": "#a0522d", "rgb_color": [153, 83, 47], "sofa_type": "2-Seater", "color_name": "sienna"}
45	Flipper Sofa cum Bed - Three Seater, Omega Blue	sofa_images/sofa_43.jpg	12350	8521.5	31	1		{"hex_color": "#dcdcdc", "rgb_color": [215, 216, 223], "sofa_type": "3-Seater", "color_name": "gainsboro"}
46	Solatio Sofa - Three Seater	sofa_images/sofa_44.jpg	11998	9358.44	22	1		{"hex_color": "#2f4f4f", "rgb_color": [40, 40, 53], "sofa_type": "3-Seater", "color_name": "darkslategray"}
48	Napper L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_46.jpg	46279	38874.36	16	1		{"hex_color": "#2f4f4f", "rgb_color": [43, 43, 43], "sofa_type": "L-Shape", "color_name": "darkslategray"}
29	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Left Aligned Chaise)	sofa_images/sofa_27.jpg	42999	27949.35	35	1		{"hex_color": "#696969", "rgb_color": [81, 83, 95], "sofa_type": "3-Seater", "color_name": "dimgray"}
50	Barcelona Sofa - Three Seater	sofa_images/sofa_48.jpg	30067	26458.96	12	1		{"hex_color": "#2f4f4f", "rgb_color": [30, 53, 83], "sofa_type": "3-Seater", "color_name": "darkslategray"}
30	Magnus Sofa - Three Seater	sofa_images/sofa_28.jpg	39999	25999.35	35	1		{"hex_color": "#556b2f", "rgb_color": [111, 78, 57], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
66	Lounger Plus Sofa - (3 Seater +Left Aligned Chaise)	sofa_images/sofa_64.jpg	59123	42568.56	28	1		{"hex_color": "#696969", "rgb_color": [89, 89, 89], "sofa_type": "L-Shape", "color_name": "dimgray"}
59	Napper Plus Sofa -Three Seater Vogue Deep Ocean	sofa_images/sofa_57.jpg	37167	28618.59	23	1		{"hex_color": "#2f4f4f", "rgb_color": [33, 47, 57], "sofa_type": "3-Seater", "color_name": "darkslategray"}
68	Manila Sheesham Wood Sofa - Three Seater	sofa_images/sofa_66.jpg	33414	27399.48	18	1		{"hex_color": "#bc8f8f", "rgb_color": [181, 160, 140], "sofa_type": "3-Seater", "color_name": "rosybrown"}
61	Komodo L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_59.jpg	54999	35749.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [193, 184, 166], "sofa_type": "L-Shape", "color_name": "silver"}
69	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Left Aligned Chaise)	sofa_images/sofa_67.jpg	42999	27949.35	35	1		{"hex_color": "#a9a9a9", "rgb_color": [172, 162, 152], "sofa_type": "Sofa-Cum-Bed", "color_name": "darkgray"}
70	Magnus Sofa - Three Seater	sofa_images/sofa_68.jpg	39999	25999.35	35	1		{"hex_color": "#bc8f8f", "rgb_color": [165, 139, 111], "sofa_type": "3-Seater", "color_name": "rosybrown"}
71	Comoros Corner L Shape Sofa (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_69.jpg	84299	54794.35	35	1		{"hex_color": "#000000", "rgb_color": [5, 6, 6], "sofa_type": "L-Shape", "color_name": "black"}
74	Napper Mini Sofa - 3 Seater (1.94m*85.09cm*85.34cm) /\n                      (76.5*33.5*33.6inch)	sofa_images/sofa_72.jpg	20299	14412.29	29	1		{"hex_color": "#000000", "rgb_color": [40, 34, 30], "sofa_type": "3-Seater", "color_name": "black"}
67	Snoozepro Plus L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_65.jpg	47896	34006.16	29	1		{"hex_color": "#696969", "rgb_color": [104, 83, 85], "sofa_type": "L-Shape", "color_name": "dimgray"}
72	Lounger L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_70.jpg	38208	27127.68	29	1		{"hex_color": "#000000", "rgb_color": [23, 28, 35], "sofa_type": "L-Shape", "color_name": "black"}
73	Haverford Sofa - Two Seater	sofa_images/sofa_71.jpg	27899	16739.4	40	1		{"hex_color": "#000000", "rgb_color": [27, 30, 36], "sofa_type": "2-Seater", "color_name": "black"}
80	Fyras 2 Seater Solid wood Sofa	sofa_images/sofa_78.jpg	18599	11159.4	40	1		{"hex_color": "#2f4f4f", "rgb_color": [77, 66, 59], "sofa_type": "2-Seater", "color_name": "darkslategray"}
75	Dreamer Sofa - Three Seater	sofa_images/sofa_73.jpg	25497	20142.63	21	1		{"hex_color": "#696969", "rgb_color": [110, 122, 107], "sofa_type": "3-Seater", "color_name": "dimgray"}
76	Bahamas Sheesham Wood Sofa Set - (3+2)	sofa_images/sofa_74.jpg	44870	39036.9	13	1		{"hex_color": "#556b2f", "rgb_color": [98, 77, 50], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
56	Tahiti Sofa - Three Seater	sofa_images/sofa_54.jpg	37999	24699.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [200, 185, 174], "sofa_type": "3-Seater", "color_name": "silver"}
77	Miami Sofa - 3 Seater - Omega Blue	sofa_images/sofa_75.jpg	15200	10336	32	1		{"hex_color": "#2f4f4f", "rgb_color": [56, 62, 71], "sofa_type": "3-Seater", "color_name": "darkslategray"}
57	Belize Plus Sofa - Three Seater	sofa_images/sofa_55.jpg	32998	25078.48	24	1		{"hex_color": "#a9a9a9", "rgb_color": [133, 172, 178], "sofa_type": "3-Seater", "color_name": "darkgray"}
87	Skiver L Shape 6 Seater Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_85.jpg	26000	17680	32	1		{"hex_color": "#2f4f4f", "rgb_color": [37, 67, 106], "sofa_type": "L-Shape", "color_name": "darkslategray"}
94	SnoozePro Sofa Set	sofa_images/sofa_92.jpg	36899	27305.260000000002	26	1		{"hex_color": "#2f4f4f", "rgb_color": [25, 58, 53], "sofa_type": "L-Shape", "color_name": "darkslategray"}
82	Solomon Sofa - Single Seater	sofa_images/sofa_80.jpg	16999	11049.35	35	1		{"hex_color": "#d2b48c", "rgb_color": [193, 179, 154], "sofa_type": "1-Seater", "color_name": "tan"}
81	Solatio Sofa - Three Seater	sofa_images/sofa_79.jpg	11998	9358.44	22	1		{"hex_color": "#000000", "rgb_color": [51, 35, 13], "sofa_type": "3-Seater", "color_name": "black"}
84	Amoeba Sofa cum Bed	sofa_images/sofa_82.jpg	22157	15953.04	28	1		{"hex_color": "#2f4f4f", "rgb_color": [23, 84, 95], "sofa_type": "2-Seater", "color_name": "darkslategray"}
83	Napper Sofa Set (3+2)	sofa_images/sofa_81.jpg	47073	38599.86	18	1		{"hex_color": "#808080", "rgb_color": [138, 122, 112], "sofa_type": "3-Seater", "color_name": "gray"}
114	Amoeba Sofa cum Bed	sofa_images/sofa_112.jpg	22157	15953.04	28	1		{"hex_color": "#2f4f4f", "rgb_color": [57, 57, 57], "sofa_type": "2-Seater", "color_name": "darkslategray"}
116	Belize L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_114.jpg	34898	29663.3	15	1		{"hex_color": "#2f4f4f", "rgb_color": [32, 51, 75], "sofa_type": "L-Shape", "color_name": "darkslategray"}
126	Tasmania Sofa - Two Seater	sofa_images/sofa_124.jpg	18867	14527.59	23	1		{"hex_color": "#556b2f", "rgb_color": [83, 71, 60], "sofa_type": "2-Seater", "color_name": "darkolivegreen"}
128	Lounger Plus Sofa set (3+2) Seater	sofa_images/sofa_126.jpg	67234	48408.479999999996	28	1		{"hex_color": "#696969", "rgb_color": [123, 89, 83], "sofa_type": "2-Seater", "color_name": "dimgray"}
129	SnoozePro Plus Sofa -Two Seater Reflection Rose Brown	sofa_images/sofa_127.jpg	20999	14699.3	30	1		{"hex_color": "#808080", "rgb_color": [162, 123, 127], "sofa_type": "2-Seater", "color_name": "gray"}
132	Comoros Corner L Shape Sofa (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_130.jpg	80499	52324.35	35	1		{"hex_color": "#808080", "rgb_color": [157, 123, 86], "sofa_type": "L-Shape", "color_name": "gray"}
108	Miami Sofa - 3 Seater - Omega Pearl	sofa_images/sofa_106.jpg	15200	10336	32	1		{"hex_color": "#a9a9a9", "rgb_color": [170, 162, 157], "sofa_type": "3-Seater", "color_name": "darkgray"}
109	Havana Sofa - Three Seater Cobalt Blue	sofa_images/sofa_107.jpg	26199	20435.22	22	1		{"hex_color": "#000000", "rgb_color": [20, 27, 38], "sofa_type": "3-Seater", "color_name": "black"}
142	Tasmania Sofa - Two Seater	sofa_images/sofa_140.jpg	18867	14527.59	23	1		{"hex_color": "#000000", "rgb_color": [20, 21, 23], "sofa_type": "2-Seater", "color_name": "black"}
147	Napper Ottoman	sofa_images/sofa_145.jpg	6305	5107.05	19	1		{"hex_color": "#808080", "rgb_color": [115, 119, 127], "sofa_type": "1-Seater", "color_name": "gray"}
151	Napper Ottoman	sofa_images/sofa_149.jpg	6305	5107.05	19	1		{"hex_color": "#a9a9a9", "rgb_color": [183, 167, 155], "sofa_type": "1-Seater", "color_name": "darkgray"}
153	SnoozePro Ottoman	sofa_images/sofa_151.jpg	5897	4245.84	28	1		{"hex_color": "#808080", "rgb_color": [115, 119, 127], "sofa_type": "1-Seater", "color_name": "gray"}
155	SnoozePro Sofa - Two Seater	sofa_images/sofa_153.jpg	15199	11095.27	27	1		{"hex_color": "#a9a9a9", "rgb_color": [188, 174, 159], "sofa_type": "2-Seater", "color_name": "darkgray"}
156	SnoozePro L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_154.jpg	33800	25012	26	1		{"hex_color": "#808080", "rgb_color": [140, 118, 108], "sofa_type": "L-Shape", "color_name": "gray"}
133	Lounger L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_131.jpg	38208	27127.68	29	1		{"hex_color": "#000000", "rgb_color": [23, 28, 35], "sofa_type": "L-Shape", "color_name": "black"}
135	Dreamer L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_133.jpg	35277	27868.83	21	1		{"hex_color": "#000000", "rgb_color": [5, 6, 8], "sofa_type": "L-Shape", "color_name": "black"}
136	Bahamas Sheesham Wood Sofa - Two Seater	sofa_images/sofa_134.jpg	19594	17046.78	13	1		{"hex_color": "#556b2f", "rgb_color": [105, 78, 47], "sofa_type": "2-Seater", "color_name": "darkolivegreen"}
137	Miami Sofa - 3+2 Seater - Omega Blue	sofa_images/sofa_135.jpg	27999	19039.32	32	1		{"hex_color": "#2f4f4f", "rgb_color": [55, 61, 70], "sofa_type": "3-Seater", "color_name": "darkslategray"}
138	Havana Sofa Set (3+2) Reflection Green	sofa_images/sofa_136.jpg	49697	38763.66	22	1		{"hex_color": "#696969", "rgb_color": [109, 107, 81], "sofa_type": "3-Seater", "color_name": "dimgray"}
167	Stargazer Rocking & Revolving Recliner - 1 Seater -\n                      Amber	sofa_images/sofa_165.jpg	22500	16875	25	1		{"hex_color": "#a0522d", "rgb_color": [162, 87, 41], "sofa_type": "1-Seater", "color_name": "sienna"}
180	Stargazer Recliner - 1 Seater - Amber	sofa_images/sofa_178.jpg	18500	13690	26	1		{"hex_color": "#8b4513", "rgb_color": [112, 51, 8], "sofa_type": "1-Seater", "color_name": "saddlebrown"}
181	Amoeba Sofa cum Bed	sofa_images/sofa_179.jpg	20900	15048	28	1		{"hex_color": "#000000", "rgb_color": [7, 7, 8], "sofa_type": "2-Seater", "color_name": "black"}
182	Amoeba Sofa cum Bed	sofa_images/sofa_180.jpg	20900	15048	28	1		{"hex_color": "#a9a9a9", "rgb_color": [170, 160, 151], "sofa_type": "2-Seater", "color_name": "darkgray"}
183	Amoeba Sofa cum Bed	sofa_images/sofa_181.jpg	20900	15048	28	1		{"hex_color": "#2f4f4f", "rgb_color": [79, 74, 68], "sofa_type": "2-Seater", "color_name": "darkslategray"}
184	Dreamer Sofa - Single Seater	sofa_images/sofa_182.jpg	15830	12347.4	22	1		{"hex_color": "#2f4f4f", "rgb_color": [9, 88, 92], "sofa_type": "1-Seater", "color_name": "darkslategray"}
185	Dreamer Sofa - Two Seater	sofa_images/sofa_183.jpg	18381	14337.18	22	1		{"hex_color": "#a9a9a9", "rgb_color": [177, 169, 160], "sofa_type": "2-Seater", "color_name": "darkgray"}
88	Azores Sofa Set (3+2+1) Seater	sofa_images/sofa_86.jpg	80996	52647.4	35	1		{"hex_color": "#556b2f", "rgb_color": [92, 75, 59], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
89	Lumara Sofa Set - (3+2) Seater	sofa_images/sofa_87.jpg	46498	30223.7	35	1		{"hex_color": "#bc8f8f", "rgb_color": [160, 148, 139], "sofa_type": "3-Seater", "color_name": "rosybrown"}
186	Dreamer Sofa - Three Seater	sofa_images/sofa_184.jpg	25497	20142.63	21	1		{"hex_color": "#a9a9a9", "rgb_color": [177, 168, 159], "sofa_type": "3-Seater", "color_name": "darkgray"}
187	Dreamer Sofa - Three Seater	sofa_images/sofa_185.jpg	25497	20142.63	21	1		{"hex_color": "#696969", "rgb_color": [112, 110, 105], "sofa_type": "3-Seater", "color_name": "dimgray"}
188	Amoeba Sofa cum Bed	sofa_images/sofa_186.jpg	20900	15048	28	1		{"hex_color": "#a52a2a", "rgb_color": [190, 62, 65], "sofa_type": "2-Seater", "color_name": "brown"}
199	Muser Recliner - Electric	sofa_images/sofa_197.jpg	25001	13500.54	46	1		{"hex_color": "#bdb76b", "rgb_color": [191, 166, 122], "sofa_type": "1-Seater", "color_name": "darkkhaki"}
200	Stargazer Recliner - 1 Seater - Marble Grey	sofa_images/sofa_198.jpg	18500	13690	26	1		{"hex_color": "#2f4f4f", "rgb_color": [70, 69, 70], "sofa_type": "1-Seater", "color_name": "darkslategray"}
192	Miami Sofa - 2 Seater - Chrome Yellow	sofa_images/sofa_190.jpg	14599	9927.32	32	1		{"hex_color": "#daa520", "rgb_color": [221, 155, 2], "sofa_type": "2-Seater", "color_name": "goldenrod"}
90	Tahiti Sofa seat(3+2) Seater	sofa_images/sofa_88.jpg	69998	45498.7	35	1		{"hex_color": "#a0522d", "rgb_color": [138, 77, 43], "sofa_type": "3-Seater", "color_name": "sienna"}
91	Belize Plus L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_89.jpg	46117	38738.28	16	1		{"hex_color": "#696969", "rgb_color": [115, 66, 77], "sofa_type": "L-Shape", "color_name": "dimgray"}
201	Stargazer Recliner - 1 Seater - Sangria	sofa_images/sofa_199.jpg	18500	13690	26	1		{"hex_color": "#2f4f4f", "rgb_color": [86, 48, 50], "sofa_type": "1-Seater", "color_name": "darkslategray"}
9	Naxos Sofa - Three Seater	sofa_images/sofa_7.jpg	45499	29574.35	35	1		{"hex_color": "#2f4f4f", "rgb_color": [51, 66, 47], "sofa_type": "3-Seater", "color_name": "darkslategray"}
11	Skiver L Shape 6 Seater Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_9.jpg	26000	17680	32	1		{"hex_color": "#000000", "rgb_color": [20, 19, 22], "sofa_type": "L-Shape", "color_name": "black"}
12	Azores Sofa - Three Seater	sofa_images/sofa_10.jpg	33999	22099.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [202, 192, 171], "sofa_type": "3-Seater", "color_name": "silver"}
13	Lumara Sofa -Three Seater	sofa_images/sofa_11.jpg	25999	16899.35	35	1		{"hex_color": "#696969", "rgb_color": [119, 93, 82], "sofa_type": "3-Seater", "color_name": "dimgray"}
14	Tahiti Sofa - Three Seater	sofa_images/sofa_12.jpg	37999	24699.35	35	1		{"hex_color": "#a0522d", "rgb_color": [171, 104, 64], "sofa_type": "3-Seater", "color_name": "sienna"}
15	Belize Plus L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_13.jpg	49449	42526.14	14	1		{"hex_color": "#2f4f4f", "rgb_color": [35, 51, 66], "sofa_type": "L-Shape", "color_name": "darkslategray"}
195	Dreamer Sofa Set (3+2+1)	sofa_images/sofa_193.jpg	65770	51300.6	22	1		{"hex_color": "#48d1cc", "rgb_color": [64, 189, 183], "sofa_type": "3-Seater", "color_name": "mediumturquoise"}
92	Dreamer Plus L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_90.jpg	51678	43409.520000000004	16	1		{"hex_color": "#a9a9a9", "rgb_color": [179, 173, 168], "sofa_type": "L-Shape", "color_name": "darkgray"}
197	Hawaii Sofa - 3 Seater - Sky Green	sofa_images/sofa_195.jpg	14399	10655.26	26	1		{"hex_color": "#4682b4", "rgb_color": [45, 137, 143], "sofa_type": "2-Seater", "color_name": "steelblue"}
93	Napper Plus Sofa -Three Seater Reflection Mocha Brown	sofa_images/sofa_91.jpg	33998	26178.46	23	1		{"hex_color": "#bc8f8f", "rgb_color": [164, 138, 119], "sofa_type": "3-Seater", "color_name": "rosybrown"}
16	Dreamer Plus Sofa -Three Seater	sofa_images/sofa_14.jpg	35498	26268.52	26	1		{"hex_color": "#696969", "rgb_color": [143, 84, 92], "sofa_type": "3-Seater", "color_name": "dimgray"}
17	Napper Plus Sofa -Three Seater Reflection Rose Brown	sofa_images/sofa_15.jpg	33998	26178.46	23	1		{"hex_color": "#bc8f8f", "rgb_color": [167, 128, 129], "sofa_type": "3-Seater", "color_name": "rosybrown"}
202	Stargazer Recliner - 1 Seater - Tan	sofa_images/sofa_200.jpg	18500	13690	26	1		{"hex_color": "#a0522d", "rgb_color": [137, 65, 48], "sofa_type": "1-Seater", "color_name": "sienna"}
193	Miami Sofa - 3 Seater - Chrome Yellow	sofa_images/sofa_191.jpg	17197	11693.96	32	1		{"hex_color": "#daa520", "rgb_color": [221, 154, 2], "sofa_type": "3-Seater", "color_name": "goldenrod"}
18	Tuvalu Sofa without Motion - Three Seater	sofa_images/sofa_16.jpg	39999	25999.35	35	1		{"hex_color": "#696969", "rgb_color": [109, 97, 86], "sofa_type": "3-Seater", "color_name": "dimgray"}
19	Komodo Sofa - Three Seater	sofa_images/sofa_17.jpg	37499	24374.35	35	1		{"hex_color": "#c0c0c0", "rgb_color": [204, 193, 171], "sofa_type": "3-Seater", "color_name": "silver"}
20	SnoozePro Sofa - Three Seater	sofa_images/sofa_18.jpg	19600	14504	26	1		{"hex_color": "#696969", "rgb_color": [131, 108, 88], "sofa_type": "3-Seater", "color_name": "dimgray"}
21	Sicily Sofa - Three Seater	sofa_images/sofa_19.jpg	16999	13769.19	19	1		{"hex_color": "#191970", "rgb_color": [15, 36, 58], "sofa_type": "3-Seater", "color_name": "midnightblue"}
23	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Right Aligned Chaise)	sofa_images/sofa_21.jpg	42999	27949.35	35	1		{"hex_color": "#696969", "rgb_color": [90, 87, 86], "sofa_type": "3-Seater", "color_name": "dimgray"}
31	Comoros Corner L Shape Sofa (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_29.jpg	84299	54794.35	35	1		{"hex_color": "#000000", "rgb_color": [5, 4, 3], "sofa_type": "L-Shape", "color_name": "black"}
32	Lounger Sofa - Three Seater	sofa_images/sofa_30.jpg	28499	20234.29	29	1		{"hex_color": "#a9a9a9", "rgb_color": [184, 177, 168], "sofa_type": "3-Seater", "color_name": "darkgray"}
33	Hawaii Sofa - 3 Seater - Dark Blue	sofa_images/sofa_31.jpg	14399	10655.26	26	1		{"hex_color": "#483d8b", "rgb_color": [43, 82, 133], "sofa_type": "3-Seater", "color_name": "darkslateblue"}
34	Napper Mini Sofa - 3 Seater (1.94m*85.09cm*85.34cm) /\n                      (76.5*33.5*33.6inch)	sofa_images/sofa_32.jpg	20299	14412.29	29	1		{"hex_color": "#000000", "rgb_color": [21, 18, 18], "sofa_type": "3-Seater", "color_name": "black"}
35	Dreamer Sofa - Three Seater	sofa_images/sofa_33.jpg	26880	21235.2	21	1		{"hex_color": "#2f4f4f", "rgb_color": [25, 37, 54], "sofa_type": "3-Seater", "color_name": "darkslategray"}
36	Bahamas Sheesham Wood Sofa - Three Seater	sofa_images/sofa_34.jpg	25276	21990.12	13	1		{"hex_color": "#bc8f8f", "rgb_color": [170, 152, 135], "sofa_type": "3-Seater", "color_name": "rosybrown"}
37	Miami Sofa - 3 Seater - Omega Green	sofa_images/sofa_35.jpg	15200	10336	32	1		{"hex_color": "#696969", "rgb_color": [106, 124, 113], "sofa_type": "3-Seater", "color_name": "dimgray"}
51	Naxos Sofa Set (3+2) Seater	sofa_images/sofa_49.jpg	77997	50698.05	35	1		{"hex_color": "#000000", "rgb_color": [10, 11, 8], "sofa_type": "3-Seater", "color_name": "black"}
52	Belize Sofa - Three Seater	sofa_images/sofa_50.jpg	23998	20158.32	16	1		{"hex_color": "#191970", "rgb_color": [5, 37, 77], "sofa_type": "3-Seater", "color_name": "midnightblue"}
55	Lumara Sofa -Three Seater	sofa_images/sofa_53.jpg	25999	16899.35	35	1		{"hex_color": "#778899", "rgb_color": [139, 141, 145], "sofa_type": "3-Seater", "color_name": "lightslategray"}
58	Dreamer Plus Sofa -Two Seater	sofa_images/sofa_56.jpg	35498	26268.52	26	1		{"hex_color": "#696969", "rgb_color": [77, 110, 84], "sofa_type": "2-Seater", "color_name": "dimgray"}
60	Tuvalu without Motion Sofa Set (3+2) Seater	sofa_images/sofa_58.jpg	69498	45173.7	35	1		{"hex_color": "#696969", "rgb_color": [114, 104, 88], "sofa_type": "3-Seater", "color_name": "dimgray"}
62	SnoozePro Sofa - Three Seater Omega Green	sofa_images/sofa_60.jpg	19600	14504	26	1		{"hex_color": "#696969", "rgb_color": [103, 119, 104], "sofa_type": "3-Seater", "color_name": "dimgray"}
63	Sicily Sofa - Three Seater	sofa_images/sofa_61.jpg	16999	13769.19	19	1		{"hex_color": "#2f4f4f", "rgb_color": [77, 76, 82], "sofa_type": "3-Seater", "color_name": "darkslategray"}
64	Tasmania Sofa Set - (3+2) Seater	sofa_images/sofa_62.jpg	43749	33686.729999999996	23	1		{"hex_color": "#696969", "rgb_color": [125, 115, 106], "sofa_type": "3-Seater", "color_name": "dimgray"}
65	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Left Aligned Chaise)	sofa_images/sofa_63.jpg	42999	27949.35	35	1		{"hex_color": "#696969", "rgb_color": [84, 94, 83], "sofa_type": "Sofa-Cum-Bed", "color_name": "dimgray"}
194	Miami Sofa - 3 Seater - Ash Grey	sofa_images/sofa_192.jpg	17197	11693.96	32	1		{"hex_color": "#696969", "rgb_color": [87, 88, 83], "sofa_type": "3-Seater", "color_name": "dimgray"}
196	Stargazer Recliner - 1 Seater - Dark Fantasy	sofa_images/sofa_194.jpg	18500	13690	26	1		{"hex_color": "#2f4f4f", "rgb_color": [80, 56, 56], "sofa_type": "1-Seater", "color_name": "darkslategray"}
198	Stargazer Recliner - Rocking & Revolving	sofa_images/sofa_196.jpg	22500	16875	25	1		{"hex_color": "#696969", "rgb_color": [104, 84, 79], "sofa_type": "1-Seater", "color_name": "dimgray"}
78	Havana Sofa - Three Seater Malibu Green	sofa_images/sofa_76.jpg	26199	20435.22	22	1		{"hex_color": "#2f4f4f", "rgb_color": [3, 53, 59], "sofa_type": "3-Seater", "color_name": "darkslategray"}
79	Naples Sofa cum Bed - Three Seater, Cobalt Blue	sofa_images/sofa_77.jpg	16170	12612.6	22	1		{"hex_color": "#000000", "rgb_color": [3, 2, 2], "sofa_type": "3-Seater", "color_name": "black"}
85	Barcelona L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_83.jpg	36436	31334.96	14	1		{"hex_color": "#c0c0c0", "rgb_color": [198, 188, 174], "sofa_type": "L-Shape", "color_name": "silver"}
86	Belize L Shape Sofa Set (3 Seater + Right Aligned Chaise)	sofa_images/sofa_84.jpg	35130	29860.5	15	1		{"hex_color": "#808080", "rgb_color": [136, 126, 117], "sofa_type": "L-Shape", "color_name": "gray"}
95	Sicily Sofa - Three Seater	sofa_images/sofa_93.jpg	16999	13769.19	19	1		{"hex_color": "#a9a9a9", "rgb_color": [175, 166, 152], "sofa_type": "3-Seater", "color_name": "darkgray"}
96	Tasmania Sofa Set - (3+2) Seater	sofa_images/sofa_94.jpg	43749	33686.729999999996	23	1		{"hex_color": "#191970", "rgb_color": [18, 38, 72], "sofa_type": "3-Seater", "color_name": "midnightblue"}
97	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Right Aligned Chaise)	sofa_images/sofa_95.jpg	42999	27949.35	35	1		{"hex_color": "#2f4f4f", "rgb_color": [84, 75, 71], "sofa_type": "Sofa-Cum-Bed", "color_name": "darkslategray"}
98	Lounger Plus Sofa set (3+1+1) Seater	sofa_images/sofa_96.jpg	89278	64280.16	28	1		{"hex_color": "#a9a9a9", "rgb_color": [186, 175, 162], "sofa_type": "3-Seater", "color_name": "darkgray"}
99	SnoozePro Plus Sofa Set - (3+2+1) Reflection Mocha Brown	sofa_images/sofa_97.jpg	62998	44098.6	30	1		{"hex_color": "#556b2f", "rgb_color": [100, 80, 68], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
100	Manila Sheesham Wood Sofa Set - (3+2+1)	sofa_images/sofa_98.jpg	82242	66616.02	19	1		{"hex_color": "#000000", "rgb_color": [28, 18, 10], "sofa_type": "3-Seater", "color_name": "black"}
101	Magnus Sofa Set - (3+2)	sofa_images/sofa_99.jpg	74998	48748.7	35	1		{"hex_color": "#556b2f", "rgb_color": [113, 79, 58], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
102	Comoros Corner L Shape Sofa (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_100.jpg	80499	52324.35	35	1		{"hex_color": "#000000", "rgb_color": [7, 6, 5], "sofa_type": "L-Shape", "color_name": "black"}
103	Lounger Sofa - Three Seater	sofa_images/sofa_101.jpg	27585	19585.35	29	1		{"hex_color": "#000000", "rgb_color": [18, 27, 47], "sofa_type": "3-Seater", "color_name": "black"}
104	Haverford Sofa - Single Seater	sofa_images/sofa_102.jpg	20097	12058.2	40	1		{"hex_color": "#000000", "rgb_color": [15, 18, 22], "sofa_type": "1-Seater", "color_name": "black"}
105	Napper Mini Sofa - 3 Seater Omega Green	sofa_images/sofa_103.jpg	20299	14412.29	29	1		{"hex_color": "#808080", "rgb_color": [111, 126, 116], "sofa_type": "3-Seater", "color_name": "gray"}
106	Dreamer Sofa Set (3+2)	sofa_images/sofa_104.jpg	48238	37625.64	22	1		{"hex_color": "#2f4f4f", "rgb_color": [25, 37, 54], "sofa_type": "3-Seater", "color_name": "darkslategray"}
107	Bahamas Sheesham Wood Sofa Set - (3+2)	sofa_images/sofa_105.jpg	45684	39745.08	13	1		{"hex_color": "#000000", "rgb_color": [24, 25, 29], "sofa_type": "3-Seater", "color_name": "black"}
110	Naples Sofa - Three Seater, Omega Pearl	sofa_images/sofa_108.jpg	14998	11548.46	23	1		{"hex_color": "#a9a9a9", "rgb_color": [167, 161, 150], "sofa_type": "3-Seater", "color_name": "darkgray"}
111	Fyras 1 Seater Solid wood Sofa	sofa_images/sofa_109.jpg	13619	8171.4	40	1		{"hex_color": "#bc8f8f", "rgb_color": [175, 147, 125], "sofa_type": "1-Seater", "color_name": "rosybrown"}
112	Solomon Sofa Set (3+2+1) Seater	sofa_images/sofa_110.jpg	75497	49073.05	35	1		{"hex_color": "#000000", "rgb_color": [13, 12, 7], "sofa_type": "3-Seater", "color_name": "black"}
113	Napper Sofa Set - Three Seater	sofa_images/sofa_111.jpg	25000	21000	16	1		{"hex_color": "#808080", "rgb_color": [112, 128, 118], "sofa_type": "3-Seater", "color_name": "gray"}
115	Barcelona Sofa - Three Seater	sofa_images/sofa_113.jpg	27300	24024	12	1		{"hex_color": "#808080", "rgb_color": [125, 138, 130], "sofa_type": "3-Seater", "color_name": "gray"}
117	Skiver L Shape 6 Seater Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_115.jpg	26000	17680	32	1		{"hex_color": "#2f4f4f", "rgb_color": [52, 50, 65], "sofa_type": "L-Shape", "color_name": "darkslategray"}
118	Azores Sofa Set (3+2) Seater	sofa_images/sofa_116.jpg	61998	40298.7	35	1		{"hex_color": "#2f4f4f", "rgb_color": [72, 60, 57], "sofa_type": "3-Seater", "color_name": "darkslategray"}
119	Lumara Sofa Set - (3+1+1) Seater	sofa_images/sofa_117.jpg	55996	36397.4	35	1		{"hex_color": "#808080", "rgb_color": [133, 120, 111], "sofa_type": "3-Seater", "color_name": "gray"}
120	Tahiti Sofa seat(3+2) Seater	sofa_images/sofa_118.jpg	69998	45498.7	35	1		{"hex_color": "#c0c0c0", "rgb_color": [210, 200, 188], "sofa_type": "3-Seater", "color_name": "silver"}
121	Belize Plus Sofa Set - (3+2)	sofa_images/sofa_119.jpg	55676	41757	25	1		{"hex_color": "#808080", "rgb_color": [154, 142, 127], "sofa_type": "3-Seater", "color_name": "gray"}
122	Dreamer Plus Sofa Set - (3+2)	sofa_images/sofa_120.jpg	61973	45860.020000000004	26	1		{"hex_color": "#708090", "rgb_color": [87, 121, 137], "sofa_type": "3-Seater", "color_name": "slategray"}
123	Napper Plus Sofa Set - (3+2) Reflection Rose Brown	sofa_images/sofa_121.jpg	59692	45962.84	23	1		{"hex_color": "#808080", "rgb_color": [163, 123, 125], "sofa_type": "3-Seater", "color_name": "gray"}
124	SnoozePro Sofa Set (3+2)	sofa_images/sofa_122.jpg	34397	25109.809999999998	27	1		{"hex_color": "#696969", "rgb_color": [131, 108, 88], "sofa_type": "3-Seater", "color_name": "dimgray"}
125	Sicily Sofa - Three Seater	sofa_images/sofa_123.jpg	17839	14449.59	19	1		{"hex_color": "#696969", "rgb_color": [83, 83, 94], "sofa_type": "3-Seater", "color_name": "dimgray"}
127	Napper Convertible L Shape Sofa Cum Bed with Storage (2\n                      Seater + Right Aligned Chaise)	sofa_images/sofa_125.jpg	42999	27949.35	35	1		{"hex_color": "#696969", "rgb_color": [80, 82, 95], "sofa_type": "Sofa-Cum-Bed", "color_name": "dimgray"}
130	Manila Sheesham Wood Sofa Set - (3+2)	sofa_images/sofa_128.jpg	63145	51147.45	19	1		{"hex_color": "#556b2f", "rgb_color": [81, 68, 56], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
131	Magnus Sofa Set - (3+2)	sofa_images/sofa_129.jpg	74998	48748.7	35	1		{"hex_color": "#bc8f8f", "rgb_color": [174, 152, 125], "sofa_type": "3-Seater", "color_name": "rosybrown"}
134	Napper Mini Sofa - 3 Seater (1.94m*85.09cm*85.34cm) /\n                      (76.5*33.5*33.6inch)	sofa_images/sofa_132.jpg	20299	14412.29	29	1		{"hex_color": "#808080", "rgb_color": [138, 122, 112], "sofa_type": "3-Seater", "color_name": "gray"}
139	Naples Sofa cum Bed - Three Seater, Omega Ash Grey	sofa_images/sofa_137.jpg	14998	11548.46	23	1		{"hex_color": "#2f4f4f", "rgb_color": [63, 63, 63], "sofa_type": "3-Seater", "color_name": "darkslategray"}
140	Lounger Plus Sofa -Three Seater	sofa_images/sofa_138.jpg	40310	29023.2	28	1		{"hex_color": "#2f4f4f", "rgb_color": [43, 56, 67], "sofa_type": "3-Seater", "color_name": "darkslategray"}
141	Napper Storage L Shape Sofa Set (3 Seater + Right Aligned\n                      Chaise)	sofa_images/sofa_139.jpg	46173	33706.29	27	1		{"hex_color": "#000000", "rgb_color": [5, 4, 4], "sofa_type": "L-Shape", "color_name": "black"}
143	Napper Storage L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_141.jpg	46173	33706.29	27	1		{"hex_color": "#000000", "rgb_color": [7, 7, 7], "sofa_type": "L-Shape", "color_name": "black"}
144	Flipper Sofa cum Bed - Three Seater, Omega Ash Grey	sofa_images/sofa_142.jpg	12350	8521.5	31	1		{"hex_color": "#2f4f4f", "rgb_color": [57, 53, 49], "sofa_type": "3-Seater", "color_name": "darkslategray"}
145	Tasmania Sofa - Three Seater	sofa_images/sofa_143.jpg	25001	19250.77	23	1		{"hex_color": "#8b4513", "rgb_color": [129, 58, 14], "sofa_type": "3-Seater", "color_name": "saddlebrown"}
146	Napper Sofa - Single Seater	sofa_images/sofa_144.jpg	14526	12056.58	17	1		{"hex_color": "#000000", "rgb_color": [22, 19, 18], "sofa_type": "3-Seater", "color_name": "black"}
148	Napper L Shape Sofa Set (3 Seater + Left Aligned Chaise)	sofa_images/sofa_146.jpg	41665	34581.95	17	1		{"hex_color": "#708090", "rgb_color": [108, 117, 128], "sofa_type": "L-Shape", "color_name": "slategray"}
149	Napper L Shape Sofa Set (3 Seater + Left Aligned Chaise\n                      with Ottoman)	sofa_images/sofa_147.jpg	46733	37853.729999999996	19	1		{"hex_color": "#2f4f4f", "rgb_color": [70, 74, 88], "sofa_type": "L-Shape", "color_name": "darkslategray"}
150	Napper Sofa - Three Seater	sofa_images/sofa_148.jpg	25000	21000	16	1		{"hex_color": "#808080", "rgb_color": [138, 122, 112], "sofa_type": "3-Seater", "color_name": "gray"}
152	SnoozePro Sofa - Three Seater	sofa_images/sofa_150.jpg	13799	10073.27	27	1		{"hex_color": "#2f4f4f", "rgb_color": [76, 77, 86], "sofa_type": "3-Seater", "color_name": "darkslategray"}
154	SnoozePro L Shape Sofa Set (3 Seater + Left Aligned\n                      Chaise)	sofa_images/sofa_152.jpg	33800	25012	26	1		{"hex_color": "#2f4f4f", "rgb_color": [47, 38, 40], "sofa_type": "L-Shape", "color_name": "darkslategray"}
157	SnoozePro Sofa - Three Seater	sofa_images/sofa_155.jpg	15199	11095.27	27	1		{"hex_color": "#556b2f", "rgb_color": [83, 75, 66], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
158	SnoozePro Sofa - Three Seater	sofa_images/sofa_156.jpg	19600	14504	26	1		{"hex_color": "#556b2f", "rgb_color": [83, 75, 66], "sofa_type": "3-Seater", "color_name": "darkolivegreen"}
159	Lounger Sofa - Three Seater	sofa_images/sofa_157.jpg	18081	12656.7	30	1		{"hex_color": "#696969", "rgb_color": [106, 88, 79], "sofa_type": "3-Seater", "color_name": "dimgray"}
160	Lounger Sofa - Three Seater	sofa_images/sofa_158.jpg	24315	16777.35	31	1		{"hex_color": "#696969", "rgb_color": [106, 88, 79], "sofa_type": "3-Seater", "color_name": "dimgray"}
161	Lounger Sofa - Three Seater	sofa_images/sofa_159.jpg	30646	21758.66	29	1		{"hex_color": "#696969", "rgb_color": [106, 88, 79], "sofa_type": "3-Seater", "color_name": "dimgray"}
162	SnoozePro Sofa - Three Seater	sofa_images/sofa_160.jpg	21399	15835.26	26	1		{"hex_color": "#2f4f4f", "rgb_color": [24, 36, 58], "sofa_type": "3-Seater", "color_name": "darkslategray"}
163	Napper Sofa - Three Seater	sofa_images/sofa_161.jpg	14189	11776.869999999999	17	1		{"hex_color": "#2f4f4f", "rgb_color": [37, 37, 34], "sofa_type": "3-Seater", "color_name": "darkslategray"}
164	Napper Sofa - Three Seater	sofa_images/sofa_162.jpg	21057	17477.31	17	1		{"hex_color": "#000000", "rgb_color": [20, 20, 19], "sofa_type": "3-Seater", "color_name": "black"}
165	Napper Sofa - Three Seater	sofa_images/sofa_163.jpg	27814	23363.760000000002	16	1		{"hex_color": "#000000", "rgb_color": [11, 17, 33], "sofa_type": "3-Seater", "color_name": "black"}
166	Napper Sofa - Three Seater	sofa_images/sofa_164.jpg	27814	23363.760000000002	16	1		{"hex_color": "#2f4f4f", "rgb_color": [37, 37, 34], "sofa_type": "3-Seater", "color_name": "darkslategray"}
168	SnoozePro Ottoman	sofa_images/sofa_166.jpg	6599	4751.28	28	1		{"hex_color": "#2f4f4f", "rgb_color": [35, 41, 71], "sofa_type": "1-Seater", "color_name": "darkslategray"}
169	Napper Ottoman	sofa_images/sofa_167.jpg	7094	5746.14	19	1		{"hex_color": "#191970", "rgb_color": [25, 29, 51], "sofa_type": "1-Seater", "color_name": "midnightblue"}
170	Napper Ottoman	sofa_images/sofa_168.jpg	7094	5746.14	19	1		{"hex_color": "#696969", "rgb_color": [84, 85, 82], "sofa_type": "1-Seater", "color_name": "dimgray"}
171	Napper L Shape Sofa Set (3 Seater + Left Aligned Chaise)	sofa_images/sofa_169.jpg	46279	38874.36	16	1		{"hex_color": "#2f4f4f", "rgb_color": [43, 42, 42], "sofa_type": "L-Shape", "color_name": "darkslategray"}
172	Lounger Sofa - Three Seater	sofa_images/sofa_170.jpg	21758	15230.6	30	1		{"hex_color": "#000000", "rgb_color": [18, 27, 47], "sofa_type": "3-Seater", "color_name": "black"}
173	Lounger Sofa 3 Seater	sofa_images/sofa_171.jpg	64874	45411.8	30	1		{"hex_color": "#2f4f4f", "rgb_color": [43, 43, 43], "sofa_type": "3-Seater", "color_name": "darkslategray"}
174	Lounger Sofa - Three Seater	sofa_images/sofa_172.jpg	27585	19585.35	29	1		{"hex_color": "#2f4f4f", "rgb_color": [14, 49, 45], "sofa_type": "3-Seater", "color_name": "darkslategray"}
175	Lounger Sofa - Three Seater	sofa_images/sofa_173.jpg	22577	15578.130000000001	31	1		{"hex_color": "#2f4f4f", "rgb_color": [62, 63, 67], "sofa_type": "3-Seater", "color_name": "darkslategray"}
176	Lounger Sofa - Three Seater	sofa_images/sofa_174.jpg	28499	20234.29	29	1		{"hex_color": "#2f4f4f", "rgb_color": [62, 63, 67], "sofa_type": "3-Seater", "color_name": "darkslategray"}
177	Lounger Sofa 3 Seater	sofa_images/sofa_175.jpg	50567	34891.229999999996	31	1		{"hex_color": "#2f4f4f", "rgb_color": [62, 63, 67], "sofa_type": "3-Seater", "color_name": "darkslategray"}
178	Lounger Sofa - Three Seater	sofa_images/sofa_176.jpg	22577	15578.130000000001	31	1		{"hex_color": "#696969", "rgb_color": [124, 111, 98], "sofa_type": "3-Seater", "color_name": "dimgray"}
179	Lounger Sofa 3 Seater	sofa_images/sofa_177.jpg	50567	34891.229999999996	31	1		{"hex_color": "#696969", "rgb_color": [124, 111, 98], "sofa_type": "3-Seater", "color_name": "dimgray"}
189	Miami Sofa - 2 Seater - Omega Blue	sofa_images/sofa_187.jpg	9999	6899.3099999999995	31	1		{"hex_color": "#2f4f4f", "rgb_color": [55, 61, 70], "sofa_type": "2-Seater", "color_name": "darkslategray"}
190	Miami Sofa - 3+2+1 Seater - Omega Blue	sofa_images/sofa_188.jpg	37897	25769.96	32	1		{"hex_color": "#2f4f4f", "rgb_color": [55, 61, 70], "sofa_type": "3-Seater", "color_name": "darkslategray"}
191	Miami Sofa - 3 Seater - Omega Grey	sofa_images/sofa_189.jpg	15200	10336	32	1		{"hex_color": "#696969", "rgb_color": [97, 97, 93], "sofa_type": "3-Seater", "color_name": "dimgray"}
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-01-16 17:21:12.739987+05:30	2	Solatio Sofa - Three Seater	3		7	1
2	2025-01-16 17:21:12.745213+05:30	1	Flipper Sofa Cum Bed - Three Seater (6'x5') Feet- WarpKnit\n                      Grey	3		7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	couch_management	sofa
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-01-16 16:48:13.690424+05:30
2	auth	0001_initial	2025-01-16 16:48:13.770333+05:30
3	admin	0001_initial	2025-01-16 16:48:13.792401+05:30
4	admin	0002_logentry_remove_auto_add	2025-01-16 16:48:13.798717+05:30
5	admin	0003_logentry_add_action_flag_choices	2025-01-16 16:48:13.803884+05:30
6	contenttypes	0002_remove_content_type_name	2025-01-16 16:48:13.813124+05:30
7	auth	0002_alter_permission_name_max_length	2025-01-16 16:48:13.820036+05:30
8	auth	0003_alter_user_email_max_length	2025-01-16 16:48:13.825175+05:30
9	auth	0004_alter_user_username_opts	2025-01-16 16:48:13.830514+05:30
10	auth	0005_alter_user_last_login_null	2025-01-16 16:48:13.835949+05:30
11	auth	0006_require_contenttypes_0002	2025-01-16 16:48:13.838405+05:30
12	auth	0007_alter_validators_add_error_messages	2025-01-16 16:48:13.84347+05:30
13	auth	0008_alter_user_username_max_length	2025-01-16 16:48:13.851026+05:30
14	auth	0009_alter_user_last_name_max_length	2025-01-16 16:48:13.85633+05:30
15	auth	0010_alter_group_name_max_length	2025-01-16 16:48:13.861948+05:30
16	auth	0011_update_proxy_permissions	2025-01-16 16:48:13.867089+05:30
17	auth	0012_alter_user_first_name_max_length	2025-01-16 16:48:13.872418+05:30
18	couch_management	0001_initial	2025-01-16 16:48:13.878878+05:30
19	sessions	0001_initial	2025-01-16 16:48:13.888816+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
5vqszi1ghkbwgmuhc9ps8cmkcwzbyq3l	.eJxVjDsOAjEMBe-SGkXki0NJzxlWtuOQBZRI-6kQd4eVtoD2zcx7qQHXpQ7rLNMwZnVWRh1-N0J-SNtAvmO7dc29LdNIelP0Tmd97Vmel939O6g412-dXOGUKBcb0Tk8AXiTJLpQ0IulIJyD8RKBCY5iLVhmCECuGAZCr94f7ms4Qw:1tYNxl:nmq1T2TEXh6IEceqw6b-0Io2g29222K7bgwwUsDWPK4	2025-01-30 16:53:01.666863+05:30
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 28, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: couch_management_sofa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.couch_management_sofa_id_seq', 202, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 2, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 7, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: couch_management_sofa couch_management_sofa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.couch_management_sofa
    ADD CONSTRAINT couch_management_sofa_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

