# Generated by Django 4.2.18 on 2025-01-16 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sofa_images/')),
                ('price', models.FloatField()),
                ('original_price', models.FloatField()),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
